### PR TITLE
enhance(build): warn only once about missing BLOG_ROOT

### LINKED ISSUE #10262: `'BLOG_ROOT' not set in .env file` shouldn't be in loop when build site
When I run `yarn dev`, I will get 
```
...
$ NODE_OPTIONS='--no-warnings=ExperimentalWarning --loader ts-node/esm' node ./tool/cli.ts spas
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
'BLOG_ROOT' not set in .env file
Built 146 SPA related files
$ NODE_OPTIONS='--no-warnings=ExperimentalWarning --loader ts-node/esm' node ./tool/cli.ts gather-git-history
Wrote 9 _githistory.json files
$ NODE_OPTIONS='--no-warnings=ExperimentalWarning --loader ts-node/esm' node ./tool/cli.ts build-robots-txt
info: Generated client\build\robots.txt based on ALWAYS_ALLOW_ROBOTS=false
[OKAY] Loaded ENV .env File as KEY=VALUE Format
...
```
`'BLOG_ROOT' not set in .env file` should only appear once, multiple occurrences will give the impression that something wrong.

### PR DESCRIPTION
**Pull request by awxiaoxian2020**
## Summary

Fixes #10262.

### Problem

Warn `'BLOG_ROOT' not set in .env file` multiple times in console.

### Solution

Move warning to top level.

---

### Before

console1

### After

console2

---

## How did you test this change?

run `yarn dev`.

### CODE REVIEW

File: build/utils.ts [hunk 1]
```diff
@@ -313,11 +313,6 @@ export function makeTOC(doc) {
 }
 
 export function findPostFileBySlug(slug: string): string | null {
```
Comment (fiji-flo) [inline build/utils.ts:315]: This is still used in other places so we just remove the warning.
```suggestion
export function findPostFileBySlug(slug: string): string | null {
  if (!BLOG_ROOT) {
    return null;
  }
```

File: build/spas.ts [hunk 2]
```diff
@@ -304,7 +305,7 @@ export async function buildSPAs(options: {
                   tag: parents.length > 2 ? parents[1] : null,
                 };
               }
-            } else if (segment === "blog") {
+            } else if (segment === "blog" && BLOG_ROOT) {
```
Comment (fiji-flo) [inline build/spas.ts:308]: Not needed anymore since we keep returning `null`
```suggestion
            } else if (segment === "blog") {
```

File: build/spas.ts [hunk 3]
```diff
@@ -19,6 +19,7 @@ import {
   CONTENT_TRANSLATED_ROOT,
   CONTRIBUTOR_SPOTLIGHT_ROOT,
   BUILD_OUT_ROOT,
+  BLOG_ROOT,
```
Comment (fiji-flo) [inline build/spas.ts:22]:
```suggestion
```

**Review by fiji-flo — CHANGES_REQUESTED** [review]
Thanks a lot. Some minor changes because `findPostFileBySlug` is still used and it must return null. So it's cleaner if we check for `BLOG_ROOT` in there.

If you add my suggested changes this is great and we'll approve.

**Review by caugner — APPROVED** [review]
LGTU (@argl @fiji-flo @caugner), thanks! 🎉
