### PR TITLE
fix regression of embedlivesample fallback algorithm

### LINKED ISSUE #4883: EmbedLiveSample macro regression
### Reference
https://github.com/mdn/yari/pull/3973
https://github.com/mdn/content/issues/3548
https://github.com/mdn/content/discussions/5803

### Problem
The pull request https://github.com/mdn/yari/pull/3973 introduced a nice fallback algorithm if the heading ID passed into an `EmbedLiveSample` macro couldn't be found. The fallback algorithm was important because it made live samples less fragile, especially for translated documents.

For some unknown reason, that fallback algorithm is no longer working.

cc @wbamberg

### PR DESCRIPTION
**Pull request by escattone**
Fixes #4883 

#### Testing
I modified `files/en-us/web/css/_colon_active/index.md` locally. I removed the argument to both of its `EmbedLiveSample` macro calls (so they both became simply `EmbedLiveSample()`), and then reloaded http://localhost:5000/en-US/docs/web/css/:active.

### CODE REVIEW

File: kumascript/src/api/util.js [hunk 1]
```diff
@@ -280,7 +280,10 @@ class HTMLTool {
       }
       return result;
     } else {
-      const result = collectClosestCode(findSectionStart(this.$, sectionID));
+      // We're here because we can't find the sectionID, so instead we're going
+      // to find the live-sample iframe by its id (iframeID, NOT sectionID), and
+      // then collect the closest blocks of code for the live sample.
+      const result = collectClosestCode(findSectionStart(this.$, iframeID));
```
Comment (escattone) [inline kumascript/src/api/util.js:286]: This corrects the bug introduced by #4535.

**Comment by escattone** [comment]
@wbamberg I realize that it's probably unfair to ask you to review the details of this, so removing you as a reviewer, but commenting here just as an FYI.
