### PR TITLE
fix(bcd): hide the prefix symbol if feature has unprefixed full support as well

### LINKED ISSUE #5709: Invalid statement that vendor prefix is required
In browser compatibility table, sometimes icon "Requires a vendor prefix or different name for use" is shown, even though non-prefixed version is fully supported.
That's the case for example with [Flex Flow](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow#browser_compatibility), which was supported in [Firefox 28](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/28#css), but prefixed version was added in [Firefox 49](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/49#compatibility) for compatibility reasons. Now Compatibility Table implies that vendor prefix is required if we wish to use this feature, but that's not true.
In [browser-compat-data](https://github.com/mdn/browser-compat-data/blob/main/css/properties/flex-flow.json) it looks like this:
`            "firefox": [
              {
                "version_added": "28"
              },
              {
                "prefix": "-webkit-",
                "version_added": "49"
              }
            ],`

I believe it would be best to omit showing "Requires a vendor prefix or different name for use.", when "version_added" without prefix has lower value than "version_added" with prefix.

### PR DESCRIPTION
**Pull request by danielhjacobs**
## Summary

Fixes #5709

### Problem

When a vendor prefix was added after full support already existed for compatibility reasons, it showed as if it was needed.

### Solution

Stop showing vendor prefix symbol in un-expanded table if full support already existed. 

---

### Before

https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow#browser_compatibility
Screenshot from 2022-03-22 10-38-20
https://developer.mozilla.org/en-US/docs/Web/API/Window#browser_compatibility
Screenshot from 2022-03-22 10-38-27

### After

http://localhost:3000/en-US/docs/Web/CSS/flex-flow#browser_compatibility
Screenshot from 2022-03-22 10-38-31
http://localhost:3000/en-US/docs/Web/API/Window#browser_compatibility
Screenshot from 2022-03-22 10-38-34

### CODE REVIEW

File: client/src/document/ingredients/browser-compatibility-table/utils.ts [hunk 1]
```diff
@@ -70,3 +70,16 @@ export function hasNoteworthyNotes(support: bcd.SimpleSupportStatement) {
...
+
+export function needsPrefix(support: bcd.SupportStatement | undefined) {
+  return (
+    support &&
+    getFirst(support).prefix &&
+    !asList(support).some(
+      (item) =>
+        Object.keys(item).filter(
+          (x) => !["version_added", "release_date"].includes(x)
+        ).length === 0
```
Comment (caugner) [inline client/src/document/ingredients/browser-compatibility-table/utils.ts:82]: This might break if we add an additional key to `bcd.SupportStatement`, so let's be explicit:

```suggestion
        item.version_added
        && !item.version_removed
        && !item.partial_implementation
        && !item.alternative_name
        && !item.flags
        && !item.prefix
```

File: client/src/document/ingredients/browser-compatibility-table/utils.ts [hunk 2]
```diff
@@ -70,3 +70,16 @@ export function hasNoteworthyNotes(support: bcd.SimpleSupportStatement) {
     !support.partial_implementation
   );
 }
+
+export function needsPrefix(support: bcd.SupportStatement | undefined) {
```
Comment (caugner) [inline client/src/document/ingredients/browser-compatibility-table/utils.ts:74]: Maybe `requiresPrefix` like in the title?

```suggestion
export function requiresPrefix(support: bcd.SupportStatement | undefined) {
```

**Review by caugner — CHANGES_REQUESTED** [review]
LGTM, but I have to suggestions.

File: client/src/document/ingredients/browser-compatibility-table/utils.ts (hunk 1 above)
Comment (danielhjacobs) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts:82]: Ok, should I also change https://github.com/mdn/yari/blob/main/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx#L386-L391? That's where I got this check

Comment (danielhjacobs) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts:82]: This check was added in https://github.com/mdn/yari/pull/3864

Comment (caugner) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts:82]: Good point! Can you tell me what you think those lines (389-392 and 398-400) do? Something like `hasFullSupport(item)` and `hasNoSupport(item)`?

This is exactly why I prefer self-documenting functions (and you add one in this PR, so that's great!). 😄

Comment (danielhjacobs) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts]: I don't know the exact best phrasing for the internal function, but I'm thinking something like:
```
function hasSpecialProperty(support: bcd.SimpleSupportStatement) {
  return (
    support.version_removed ||
    support.partial_implementation ||
    support.alternative_name ||
    support.flags ||
    support.prefix
  );
}

export function hasFullSupport(support: bcd.SimpleSupportStatement) {
  return (
    support.version_added && !hasSpecialProperty(support)
  );
}

export function hasNoSupport(support: bcd.SimpleSupportStatement) {
  return (
    !support.version_added && !hasSpecialProperty(support)
  );
}
```

Comment (danielhjacobs) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts]: I seem to be unable to push these changes right now: https://www.githubstatus.com/

Comment (caugner) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts]: Instead of `hasSpecialProperty()`, maybe `has[Some]Limitation()` or `has[Some]Restriction()`?

And I have to admit that the existing `hasNoSupport()` logic is not really intuitive to me. If we have `!support.version_added` but `support.version_removed`, doesn't this also mean "No support"? 🤔

Comment (danielhjacobs) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts]: Can you think of anything that you've seen with a version removed but no version added? I can't find anything like that. Maybe this just works because such an item doesn't exist.

Comment (danielhjacobs) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts]: Actually, I just realized what this check is really doing. It's not just checking if there's no support. It's checking if there's no support and no other messaging is going to appear. It's not what determines if the symbol shows (that's in CellText), it's what determines if the line "No support" shows.

Comment (danielhjacobs) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts]: Screenshot from 2022-03-22 14-34-21

**Comment by danielhjacobs** [comment]
I fixed navigator (https://developer.mozilla.org/en-US/docs/Web/API/Window#browser_compatibility) by using the same type of logic for alternative name.

File: client/src/document/ingredients/browser-compatibility-table/utils.ts [hunk 3]
```diff
@@ -70,3 +70,42 @@ export function hasNoteworthyNotes(support: bcd.SimpleSupportStatement) {
...
+
+export function requiresAltName(support: bcd.SupportStatement | undefined) {
+  return (
+    support &&
+    getFirst(support).alternative_name &&
+    !asList(support).some((item) => showsMessageIndicatingFullSupport(item))
+  );
+}
+
+export function requiresPrefix(support: bcd.SupportStatement | undefined) {
```
Comment (caugner) [inline client/src/document/ingredients/browser-compatibility-table/utils.ts:93]:
```suggestion
export function isOnlySupportedWithPrefix(support: bcd.SupportStatement | undefined) {
```

File: client/src/document/ingredients/browser-compatibility-table/utils.ts [hunk 4]
```diff
@@ -70,3 +70,42 @@ export function hasNoteworthyNotes(support: bcd.SimpleSupportStatement) {
...
+    support.partial_implementation ||
+    support.alternative_name ||
+    support.flags ||
+    support.prefix ||
+    support.version_removed ||
+    support.notes
+  );
+}
+
+export function requiresAltName(support: bcd.SupportStatement | undefined) {
```
Comment (caugner) [inline client/src/document/ingredients/browser-compatibility-table/utils.ts:85]:
```suggestion
export function isOnlySupportedWithAltName(support: bcd.SupportStatement | undefined) {
```

**Review by caugner — COMMENTED** [review]
Good catch as for the alternative_name!

Maybe we can still find better names for the `showsMessageIndicating*Support()` functions? See my suggestions below.

Otherwise this looks good and the changes have been approved internally.

**Comment by caugner** [comment]
Thank you @danielhjacobs, great job! 🎉
