### PR TITLE
Unexpected build errors in CI doesn't reveal which file caused it

### LINKED ISSUE #2168: Details of PR Build Process Don't Show Where Failure Ocurred
At the time I'm writing this, PR mdn/content#245 has a failing PR Build process. There appears to be a macro missing a closing bracket, but often these types of failures result from something that's mistyped earlier in the line. This makes it hard enough to find the error. When the information printed on scree doesn't even show where it thinks the error is, we don't have a place to start when looking for it.

image

### LINKED ISSUE #2169: Unexpected build errors in CI doesn't reveal which file caused it
One thing specifically, the CI build log doesn’t show the `buildDocumentFromURL(/en-us/docs/web/api/csspropertyrule)` information about the relevant content directory path, which I can see that my local Yari is logging. (Although in this case, even having that additional info about the affected directory still isn’t enough detail to be able to troubleshoot any further.)

_Originally posted by @sideshowbarker in https://github.com/mdn/yari/issues/2168#issuecomment-746636933_

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #2169
Fixes #2168

Here's what you'd see in `localhost:3000` if you accidentally introduce something to the raw (KS) HTML that can't even be parsed:
Screen Shot 2020-12-16 at 4 03 29 PM

It's not gorgeous but it's sufficiently informative and that's what matters. 

This is what you'd see if you use `yarn build` (which is what we use the PR Build in CI on the mdn/content repo):
```
▶ yarn build /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/index.html
yarn run v1.22.10
$ cross-env NODE_ENV=production node build/cli.js /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/index.html

Building SPAs...
Wrote /Users/peterbe/dev/MOZILLA/MDN/yari/client/build/en-us/_spas/404.html

Building Documents...
Building roots: [ '/Users/peterbe/dev/MOZILLA/MDN/content/files' ]
Error: MacroInvocationError trying to parse /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/index.html, line 36 column 62 (Expected [ \t\n\r;] or [^(} ] but "(" found.)
    at buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:207:15)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async buildDocuments (/Users/peterbe/dev/MOZILLA/MDN/yari/build/cli.js:100:9)
    at async Se._action (/Users/peterbe/dev/MOZILLA/MDN/yari/build/cli.js:279:60)
    at async Se.run (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/@caporal/core/dist/index.js:1:27579)
    at async Te._run (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/@caporal/core/dist/index.js:1:32257)

error: MacroInvocationError trying to parse /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/index.html, line 36 column 62 (Expected [ \t\n\r;] or [^(} ] but "(" found.)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

That should be enough to raise awareness of the problem.

### CODE REVIEW

**Comment by peterbe** [comment]
@escattone How do you write an end-to-end test that checks that the `yarn build` exits early and that the error message mentions the right file and line number?!
This is perhaps where a "unit test" is better. 
I think we can perhaps write a `jest` test that uses a `child_process` in some temporary file because if we add a `index.html` that is totally corrupted, into `testing/content/files/*`, then the basic testing bash script won't be able to proceed.

File: build/index.js [hunk 1]
```diff
@@ -195,7 +195,27 @@ async function buildDocument(document, documentOptions = {}) {
...
+        // But considering that this might just be one of many documents you're
+        // building, let's at least help by setting a more user-friendly error
+        // message.
+        throw new Error(
+          `MacroInvocationError trying to parse ${
+            document.fileInfo.path
+          }, line ${error.line + document.fileInfo.frontMatterOffset} column ${
+            error.column
+          } (${error.error.message})`
+        );
```
Comment (escattone) [inline build/index.js:213]: The line number is off by 1. There are two options here. First, you could take advantage of the `updateFileInfo` method of the base error class, so that would look like this:
```suggestion
        error.updateFileInfo(document.fileInfo);
        throw new Error(
          `MacroInvocationError trying to parse ${error.filepath}, line ${error.line} column ${error.column} (${error.error.message})`
        );
```

or just subtract 1 from the line caculation, so something like this:

```suggestion
        throw new Error(
          `MacroInvocationError trying to parse ${
            document.fileInfo.path
          }, line ${error.line + document.fileInfo.frontMatterOffset - 1} column ${
            error.column
          } (${error.error.message})`
        );
```

**Review by escattone — CHANGES_REQUESTED** [review]

**Review by escattone — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Beautiful. Nice work y’all in getting this coded and reviewed and landed so quick. I think it’ll help authors and reviewers a lot
