### PR TITLE
fix(page-not-found): show fallback link for moved pages

### LINKED ISSUE #5615: Localized links for redirected docs do not show fallback links
### Summary

Often, MDN links are given to users with their localization in the path from Firefox UI. Some UI links require redirects to work. If a user encounters a localized URL to a link that requires a redirect, the helpful Fallback link does not show up because the fallback checker looks at `$path/index.json` and the re-director does not know about the `/index.json` stuff.

### URL

https://developer.mozilla.org/zh-CN/docs/Mozilla/Firefox/Privacy/Storage_access_policy/Errors/CookiePartitionedForeign

should look like 

https://developer.mozilla.org/zh-CN/docs/Web/Privacy/Storage_Access_Policy/Errors/CookiePartitionedForeign

### Reproduction steps

1. Visit https://developer.mozilla.org/zh-CN/docs/Mozilla/Firefox/Privacy/Storage_access_policy/Errors/CookiePartitionedForeign
2. Observe lack of green box

### Expected behavior

I expect including a redirect for the English page should allow the internationalized versions of the "from" link should still have a suggestion box.

### Actual behavior

Including a redirect for an English page causes the internationalized link to the "from" page to no longer show the suggestion box.

### Device

Laptop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

image

### Anything else?

_No response_

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### PR DESCRIPTION
**Pull request by bvandersloot-mozilla**
## Summary

Fixes #5615

### Problem

Often, MDN links are given to users with their localization in the path from Firefox UI. Some UI links require redirects to work. If a user encounters a localized URL to a link that requires a redirect, the helpful Fallback link does not show up because the fallback checker looks at $path/index.json and the re-director does not know about the /index.json stuff.

### Solution

Instead of just looking for the English `index.json` file for the missing article, which is not typically redirected, the search proceeds in two stages:

1. Look for the English version of the article, which will follow the redirects.
2. If such an article exists, get its `index.json` file using the URL that gave a success for the article.

---

### Before

image

### After

image

---

## How did you test this change?

Manually tested locally. Ensured the new code followed the redirect and didn't break previous file-not-found boxes. Also ran relevant local tests.

### CODE REVIEW

File: client/src/page-not-found/fallback-link.tsx [hunk 1]
```diff
@@ -32,8 +32,25 @@ export default function FallbackLink({ url }: { url: string }) {
...
+        var jsonURL = response.url;
+        if (!jsonURL.endsWith("/")) {
+          jsonURL += "/";
+        }
+        jsonURL += "index.json";
+        var jsonResponse = await fetch(jsonURL);
+        if (jsonResponse.ok) {
+          const { doc } = await jsonResponse.json();
+          return doc;
+        } else if (response.status === 404) {
```
Comment (caugner) [inline client/src/page-not-found/fallback-link.tsx:51]:
```suggestion
        } else if (jsonResponse.status === 404) {
```

File: client/src/page-not-found/fallback-link.tsx [hunk 2]
```diff
@@ -32,8 +32,25 @@ export default function FallbackLink({ url }: { url: string }) {
...
+          return doc;
+        }
+        // Otherwise, use the URL that gave the successful page (potentially
+        // including any redirects) and append index.json to get the data needed
+        var jsonURL = response.url;
+        if (!jsonURL.endsWith("/")) {
+          jsonURL += "/";
+        }
+        jsonURL += "index.json";
+        var jsonResponse = await fetch(jsonURL);
```
Comment (caugner) [inline client/src/page-not-found/fallback-link.tsx:47]: Let's use `const` here:

```suggestion
        const jsonResponse = await fetch(jsonURL);
```

File: client/src/page-not-found/fallback-link.tsx [hunk 3]
```diff
@@ -32,8 +32,25 @@ export default function FallbackLink({ url }: { url: string }) {
...
-        const { doc } = await response.json();
-        return doc;
+        // If the URL is already for the JSON file, use  the response
+        if (response.url.endsWith("/index.json")) {
+          const { doc } = await response.json();
+          return doc;
+        }
+        // Otherwise, use the URL that gave the successful page (potentially
+        // including any redirects) and append index.json to get the data needed
+        var jsonURL = response.url;
```
Comment (caugner) [inline client/src/page-not-found/fallback-link.tsx:42]: Let's use `let` here, to avoid [hoisting](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting#var_hoisting):

```suggestion
        let jsonURL = response.url;
```

**Review by caugner — CHANGES_REQUESTED** [review]

**Comment by bvandersloot-mozilla** [comment]
All suggested changes are good. Thanks for the review!

I've made all of the changes in one commit on my fork.

**Review by caugner — APPROVED** [review]

**Comment by bvandersloot-mozilla** [comment]
@caugner: Can you land this? I don't have that power.

**Comment by caugner** [comment]
Thank you @bvandersloot-mozilla! 🎉
