### PR TITLE
"Join the waitlist" button cta disappears after submitting in survey

### LINKED ISSUE #3897: On mobile, the "Join the waitlist" button appears after signing up
Should be easy to reproduce with responsive design mode. 

First:
IMG_5704

After scrolling back up:
IMG_5705

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #3897

### CODE REVIEW

File: client/src/plus/app.tsx [hunk 1]
```diff
@@ -438,7 +452,16 @@ export default function App() {
               </>
             ) : (
               data &&
-              data.variant && <LandingPageSurvey variant={data.variant} />
```
Comment (dalexsy) [inline client/src/plus/app.tsx:441]: I don't know if it makes sense to hide the waitlist signup on desktop as well because it's not a pattern I've seen anywhere else.

**Review by dalexsy — CHANGES_REQUESTED** [review]
Keep the desktop button visible after signup.

File: client/src/plus/app.tsx [hunk 2]
```diff
@@ -48,12 +62,9 @@ export default function App() {
                 technical deep dives written by industry experts and powerful
                 new features to personalize your MDN experience.
               </p>
-
-              {data && data.variant && (
-                <a href="#waitlist" className="button">
-                  Join the waitlist
-                </a>
-              )}
+              <a href="#waitlist" className="button">
```
Comment (peterbe) [inline client/src/plus/app.tsx:65]: No, the `waitlist` might not load. That's why it *was* dependent on `data && data.variant` before.

**Review by dalexsy — APPROVED** [review]
