### PR TITLE
enhance(bcd): prefix titles with browser name (and version)

### LINKED ISSUE #10911: Change alt/tooltips to include the browser name due to long lists
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

### What specific section or headline is this issue about?

_No response_

### What information was incorrect, unhelpful, or incomplete?

Since https://github.com/mdn/content/issues/33075 was marked as dupe, consider the alternative mentioned at the end of the ticket, which is to add the browser name to the alt/tooltip info per cell.  Rather than just saying "Full suport", change it to say "Full support\nSafari 14.1".

### What did you expect to see?

Information about the particular browser whose cell I was hovering.

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/index.md
* Last commit: https://github.com/mdn/content/commit/37713c0c974d024ae6f695f9ae6bc7e26076ee3b
* Document last modified: 2023-10-20T14:18:14.000Z

</details>

### PR DESCRIPTION
**Pull request by jazzygasper**
## Summary

Fixes #10911 

### Problem
When looking at the compatibility table, especially for pages with long lists, you can't see the browser name when you scroll past the table header.

### Solution
Added the browser name and version number to the tooltip in each cell so it says "Full support\nSafari 14.1", instead of just "Full support".

---

### Before
Screenshot 2024-12-14 at 15 31 45

### After
Screenshot 2024-12-14 at 15 32 49

---

## How did you test this change?
Checked a page with a long compatibility list eg. http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#browser_compatibility. Hover over tick to check the browser name and version.

### CODE REVIEW

**Comment by caugner** [comment]
@jazzygasper Thanks, I pushed some changes to align the changes. Let me know what you think:

1. image
2. image
3. image

File: client/src/document/ingredients/browser-compatibility-table/feature-row.tsx [hunk 1]
```diff
@@ -139,7 +130,7 @@ const CellText = React.memo(
     const added = currentSupport?.version_added ?? null;
     const lastVersion = currentSupport?.version_last ?? null;
 
-    const browserReleaseDate = getSupportBrowserReleaseDate(support);
+    const browserReleaseDate = currentSupport?.release_date;
```
Comment (jazzygasper) [inline client/src/document/ingredients/browser-compatibility-table/feature-row.tsx:133]: Nice and concise! :)

**Comment by jazzygasper** [comment]
@caugner Yep those changes look good to me 🙌

**Review by caugner — APPROVED** [review]
