### PR TITLE
fix(markdown): support h2m cli for windows

### LINKED ISSUE #6181: `yarn md h2m` not work on windows
### Summary

This problem has been reported here: https://github.com/mdn/translated-content/discussions/2474#discussioncomment-1752165

And I find out that's because the path in windows is separated by `\` not `/`, so the regexp cannot match any path here:

https://github.com/mdn/yari/blob/e08d1aed84cbbdc7d725afbec43e8c5946065b8d/content/document.js#L476-L481

For example, when run command `yarn md h2m mdn\structures\macros --locale zh-CN --mode replace`, the `folderSearch` param will be `"mdn\\structures\\macros"` and the pured path `pure` could be `"zh-cn\\mdn\\structures\\macros\\other\\"`. So the regexp will be `/mdn\structures\macros/` and this will never match with `"mdn\\structures\\macros"`

```js
const re = new RegExp('mdn\\structures\\macros');  // /mdn\structures\macros/
const result = 'zh-cn\\mdn\\structures\\macros\\other\\'.search(re);
console.log(result); // -1
```

### URL

None

### Reproduction steps

1. set up content and translated-content repo on windows
2. set up yari repo and set `.env` file
3. run command `yarn md h2m mdn\structures\macros --locale zh-CN --mode replace`
4. result with nothing, `Document.findAll` will return `{ count: 0, iter: [GeneratorFunction: iter] }`.

### Expected behavior

`yarn md h2m` can be used on windows.

### Actual behavior

This command is not work.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

_No response_

### Anything else?

_No response_

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### PR DESCRIPTION
**Pull request by yin1999**
## Summary

Fixes #6181

### Problem

1. Windows is using `\` as path separator. So the `Document.findAll` will not math any folder with `folderSearch` arguement like this `web\javascript` (with `\` in this string).
2. The `saveProblemsReport()` won't work on windows either. Because of using `:` in file path, which is not allowed on windows.

### Solution

1. To let the `Document.findAll` works on windows, I replace the `\` in filepath with `\\`.
2. Replace `\` in `args.folder` with `/` to match the slug.
3. replace the `:` in `reportFileName` with `_` to create file on windows.

### Before

With file count: `0`.

image

### After

With file count: `809`.

image

### CODE REVIEW

File: content/document.js [hunk 1]
```diff
@@ -425,7 +425,10 @@ function findAll({
   if (folderSearch && typeof folderSearch !== "string") {
     throw new TypeError("'folderSearch' not a string");
   }
-  const folderSearchRegExp = folderSearch ? new RegExp(folderSearch) : null;
+  // replace '\' with '\\' to make this regexp works on Windows
+  const folderSearchRegExp = folderSearch
+    ? new RegExp(folderSearch.replace(/\\/g, "\\\\"))
+    : null;
```
Comment (yin1999) [inline content/document.js:431]: Or should we judge the platform here (and both replace the `/`)：

```js
  // const os = require("os");

  // replace '\' and '/' with '\\' to make this regexp works on Windows
  if (folderSearch && os.platform() === "win32") {
    folderSearch = folderSearch.replace(/\\|\//g, "\\\\");
  }

  const folderSearchRegExp = folderSearch ? new RegExp(folderSearch) : null;
```

**Review by fiji-flo — APPROVED** [review]
I don't have my Windows machine at hand but this looks more than reasonable.
