### PR TITLE
fix(theme): set color-scheme

### LINKED ISSUE #6101: Chrome shows light scrollbar in dark mode
### Summary

In Chrome, the color of the scrollbar doesn't change when switching the theme.

### URL

https://developer.mozilla.org/en-US/plus or any other page

### Reproduction steps

1. Open https://developer.mozilla.org/en-US/plus
2. Switch to dark theme.
3. Look at scrollbar.

### Expected behavior

The scrollbar should be dark, like the rest of the page.

### Actual behavior

The scrollbar is light, like the light theme.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

image

### Anything else?

Firefox is not affected.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### PR DESCRIPTION
**Pull request by caugner**
## Summary

Fixes #6101, based on #6054.

### Problem

Chrome was always showing light scrollbars, because it apparently relies on the [`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) property being set.

### Solution

1. Set the `color-scheme` property on the `:root` element (i.e. `document.documentElement` or the HTML element).
2. Set the `.dark` and `.light` classes on the `:root` element, not the `body` element.
3. Apply dark/light theme based on [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) only if `:root` element has no `dark`/`light` class.

---

### Before

image

### After

image

---

## How did you test this change?

1. Opened http://localhost:3000/en-US/docs/Web/CSS/@media/prefers-color-scheme locally in Chrome.
2. Switched theme between "OS Default" (and then used OS settings to switch), "Light" and "Dark".

### CODE REVIEW

File: libs/constants/index.js [hunk 1]
```diff
@@ -83,7 +83,7 @@ const scriptSrcValues = [
   "assets.codepen.io",
   "production-assets.codepen.io",
 
-  "'sha256-x6Tv+AdV5e6dcolO0TEo+3BG4H2nG2ACjyG8mz6QCes='", // inline no flicker
+  "'sha256-mr0WqMazG99/aIjMg/7cYeaiijSgAspY8Ssvrg63DF0='", // inline no flicker
```
Comment (caugner) [inline libs/constants/index.js:86]: @fiji-flo I used https://csplite.com/csp/sha/ to calculate this hash, but I'm not very confident that this one is right. How did you generate the hash?

**Comment by caugner** [comment]
@fiji-flo We talked about this shortly and couldn't reproduce the issue in Firefox. Turns out only Chrome-based browsers were affected, and this PR resolves that. I also added [a quick question](https://github.com/mdn/yari/pull/6102#discussion_r860355122) above.

**Review by fiji-flo — APPROVED** [review]
👍
