### PR TITLE
fix: implement market research v2 pages

### LINKED ISSUE #4128: Define and load redesigned color palette
Work with Daryl to define the final color palette that will be used for the redesign. 

- [ ] Create a color palette SASS file for the new color palette.
- [ ] Define the colors using the variables as defined in https://github.com/mdn/mdn-minimalist/blob/c57d19a3fe55c18c31f0f5887831a1d8ffe1f678/sass/vars/_mdn-web-docs-palette.scss, adding any additional colors as needed
- [ ] Load this file after the import of minimalist in order to use this new color palette.

See: https://www.figma.com/file/0XjasINHogZOxcxSmYfs4i/_Colours?node-id=26%3A265

### LINKED ISSUE #4136: Implement author meta component
As part of the hero section of deep dives, there is an author section. We should implement this as a reusable component should we wish to use it in other contexts.

https://www.figma.com/file/XWkzXs93Oo5uoMPmbr0rR6/MDN-Plus-User-Stories?node-id=92%3A194

### LINKED ISSUE #4137: Implement deep dive article layout
Implement the overall layout for deep-dive article pages(without the annotations portion):

https://www.figma.com/file/XWkzXs93Oo5uoMPmbr0rR6/MDN-Plus-User-Stories?node-id=92%3A194

### LINKED ISSUE #4138: Implement "In this series" component
Implement the "In this series" component:

https://www.figma.com/file/XWkzXs93Oo5uoMPmbr0rR6/MDN-Plus-User-Stories?node-id=92%3A194

### LINKED ISSUE #4162: Create deep dive pages(s) for Twitter research experiment
To gain more insight into people's thoughts around the deep dives, we want to set up a page that we can point readers to via Twitter.

The page will be based on the design linked too below. There is no need for a reader to navigate to or from the page.

https://www.figma.com/file/XWkzXs93Oo5uoMPmbr0rR6/MDN-Plus-User-Stories?node-id=92%3A194

The quickest way to get this done, without having to be concerned with doing double work, or breaking any styles in production is to repurpose the landing page that was used for the initial experiment.

### LINKED ISSUE #4170: Updates to Plus landing page
To reflect our revised offering, there are some updates needed to the current MDN Plus landing page. Final design to be provided.

### PR DESCRIPTION
**Pull request by schalkneethling**
Adds new v3 color scheme
Adds the overview page, deep-dive article layout as well as example articles for market research.
Includes updates to Plus landing page.

fix #4137
fix #4170 
fix #4138 
fix #4136 
fix #4162 
fix #4128

### CODE REVIEW

File: client/src/deep-dive/your-browser-support-toolkit.tsx [hunk 1]
```diff
@@ -0,0 +1,641 @@
...
+    <>
+      <div className="main-article-page-content-container girdle">
+        <article className="deep-dive-article-container">
+          <header className="main-heading-group heading-group">
+            <h1>Your browser support toolkit</h1>
+            <h2>Modern CSS in the real world : Part two</h2>
+          </header>
+          <p className="article-lead">
+            Viverra neque eget tellus, gravida pellentesque non. Purus,
+            venenatis sit ac nam nec. At vitae facilisi in mi amet aliquam.
```
Comment (peterbe) [inline client/src/deep-dive/your-browser-support-toolkit.tsx:40]: Still lorem ipsum.

File: build/spas.js [hunk 2]
```diff
@@ -59,6 +59,16 @@ async function buildSPAs(options) {
         { prefix: "signup", pageTitle: "Sign up", noIndexing: true },
         { prefix: "settings", pageTitle: "Account settings", noIndexing: true },
         { prefix: "plus", pageTitle: "Plus", noIndexing: true },
+        {
+          prefix: "plus/deep-dives/planning-for-browser-support",
+          pageTitle: "Planning for browser support ~ Plus",
+          noIndexing: true,
```
Comment (peterbe) [inline build/spas.js:65]: Note-to-self; we should cease this practice for deep dives. They ought to be indexed in Google. All of them, but only the title and the article lead. The rest of the prose should be protected by actual business logic and APIs etc.

File: client/public/assets/article-images/your-browser-support-toolkit.svg [hunk 3]
```diff
@@ -0,0 +1,9 @@
+<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 783 441" fill="none" role="img">
```
Comment (peterbe) [inline client/public/assets/article-images/your-browser-support-toolkit.svg:1]: This comment isn't about this exact `<svg ...` line but about the naming of the folder `article-images`. I think you should rename that to `deepdives`. I.e.
```
git mv client/public/assets/article-images client/public/assets/deepdives
```

**Review by peterbe — COMMENTED** [review]
@schalkneethling Please don't push more to this branch right now. I'm collecting all my feedback as an active counter-PR instead. 
It's coming to https://github.com/mdn/yari/pull/4281
I found that more productive than trying to comment on everything.

File: client/src/deep-dive/planning-for-browser-support.tsx [hunk 4]
```diff
@@ -0,0 +1,456 @@
...
+          </header>
+          <p className="article-lead">
+            Learn about the types of CSS issues you’ll be facing when working
+            with your team in a web-based environment and tips for developing a
+            future-proof support strategy.
+          </p>
+          <Byline
+            avatar="rachel-andrew.png"
+            author="Rachel Andrew"
+            authorDescription="MDN Editor &amp; Writer, Former Editor in Chief of Smashing Magazine"
```
Comment (peterbe) [inline client/src/deep-dive/planning-for-browser-support.tsx:46]:
```suggestion
            authorDescription="MDN Editor & Writer, Former Editor in Chief of Smashing Magazine"
```
when that gets rendered by the `<Byline>` component, it will escape.

File: client/src/deep-dive/planning-for-browser-support.tsx [hunk 5]
```diff
@@ -0,0 +1,456 @@
...
+            Make sure that, before you begin to plan your support strategy, you
+            are all talking about the same thing when you talk about{" "}
+            <strong>supporting a browser</strong>.
+          </p>
+          <div className="article-sidebar">
+            <p>
+              Back when Internet Explorer 6 was the main browser causing us
+              problems, the front-end team at Yahoo! came up with a useful way
+              of describing support.{" "}
+              <a href="https://github.com/yui/yui3/wiki/Graded-Browser-Support">
```
Comment (peterbe) [inline client/src/deep-dive/planning-for-browser-support.tsx:207]:
```suggestion
              <a href="https://github.com/yui/yui3/wiki/Graded-Browser-Support" className="external">
```

File: client/src/deep-dive/planning-for-browser-support.tsx [hunk 6]
```diff
@@ -0,0 +1,456 @@
...
+            devices people are using to access your site from your analytics.
+            You should be able to find out how many users are using old versions
+            of Internet Explorer, how many are on mobile devices, and which
+            versions of evergreen browsers that are in use.
+          </p>
+          <p>
+            If you don’t have your own analytics information then you could look
+            at general statistics for the locations your users are likely to be
+            in. Statcounter (
+            <a href="https://gs.statcounter.com/">
```
Comment (peterbe) [inline client/src/deep-dive/planning-for-browser-support.tsx:284]:
```suggestion
            <a href="https://gs.statcounter.com/" className="external">
```

File: client/src/deep-dive/planning-for-browser-support.tsx [hunk 7]
```diff
@@ -0,0 +1,456 @@
...
+          <h4>Core design elements vs. enhancements</h4>
+          <p>
+            As you build your site you will be testing your support policy
+            against big things, such as using CSS grid for your layout, and
+            small things — little enhancements that add some delight but
+            wouldn’t be missed if they didn’t appear.
+          </p>
+          <p>
+            For example, the{" "}
+            <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter">
```
Comment (peterbe) [inline client/src/deep-dive/planning-for-browser-support.tsx:377]:
```suggestion
            <a href="/en-US/docs/Web/CSS/backdrop-filter">
```

File: client/src/deep-dives-homepage/app.tsx [hunk 8]
```diff
@@ -0,0 +1,102 @@
+import { useParams } from "react-router-dom";
```
Comment (peterbe) [inline client/src/deep-dives-homepage/app.tsx:1]: As far as I understand, this component/file is not in use anywhere.

File: client/src/deep-dives-homepage/index.tsx [hunk 9]
```diff
@@ -0,0 +1,22 @@
...
+export function DeepDivesHomepage() {
+  const pageTitle = "MDN Plus Deep Dives";
+  React.useEffect(() => {
+    document.title = pageTitle;
+  }, []);
+  const isServer = typeof window === "undefined";
+  return (
+    <PageContentContainer extraClasses="plus deep-dives">
+      {!isServer && (
+        <React.Suspense fallback={<p>Loading...</p>}>
```
Comment (peterbe) [inline client/src/deep-dives-homepage/index.tsx:16]: Try to use the `<Loading>` component instead of `<p>`

File: client/src/plus/app.tsx [hunk 10]
```diff
@@ -1,426 +1,298 @@
 import React from "react";
```
Comment (peterbe) [inline client/src/plus/app.tsx:1]: I'm not sure where to place this comment but it bothers me that the header fonts become different. 
It's not a big deal but it "looks buggy". 
Screen Shot 2021-07-22 at 1 22 10 PM

Perhaps it's intentional. Perhaps it's deliberate. It still feels a big "huh??".

File: client/src/ui/molecules/article-meta/index.tsx [hunk 11]
```diff
@@ -0,0 +1,12 @@
+import "./index.scss";
+
+const ArticleMeta = ({ publishDate, readTime }) => {
```
Comment (peterbe) [inline client/src/ui/molecules/article-meta/index.tsx:3]: I don't know if this component is meant to stick around or if it's a quick hack to get the market research pages out. But I think we should stick to convention.
And if we're going to keep it, we should try to avoid `any` if we can for all new TS code. 
```suggestion
export function ArticleMeta({ publishDate, readTime }: {publishDate:string, readTime:string}) {
```

Comment (peterbe) [reply client/src/ui/molecules/article-meta/index.tsx:3]: Also, since this is never reused outside of `src/plus/deep-dives` I don't love that it's sitting in a global space (`ui`). 

It would have been better to put this into the article file itself.

File: client/src/ui/molecules/card/index.tsx [hunk 12]
```diff
@@ -0,0 +1,14 @@
+import "./index.scss";
+
+const Card = ({ featured, children }) => {
```
Comment (peterbe) [inline client/src/ui/molecules/card/index.tsx:3]: ditto

File: client/src/ui/molecules/series-card/index.tsx [hunk 13]
```diff
@@ -0,0 +1,25 @@
+import "./index.scss";
+
+const SeriesCard = ({ title, seriesList }) => {
```
Comment (peterbe) [inline client/src/ui/molecules/series-card/index.tsx:3]: ditto

File: client/src/ui/organisms/byline/index.tsx [hunk 14]
```diff
@@ -0,0 +1,21 @@
+import "./index.scss";
+
+const Byline = ({ avatar, author, authorDescription }) => {
```
Comment (peterbe) [inline client/src/ui/organisms/byline/index.tsx:3]: ditto

File: client/src/ui/organisms/deep-dives-feature/index.tsx [hunk 15]
```diff
@@ -0,0 +1,32 @@
+import "./index.scss";
+
+const DeepDivesFeature = () => {
```
Comment (peterbe) [inline client/src/ui/organisms/deep-dives-feature/index.tsx:3]: ditto
```suggestion
export function DeepDivesFeature() {
```

File: client/src/ui/organisms/hero/index.tsx [hunk 16]
```diff
@@ -0,0 +1,25 @@
+import "./index.scss";
+
+const Hero = () => {
```
Comment (peterbe) [inline client/src/ui/organisms/hero/index.tsx:3]: ditto
```suggestion
export function Hero() {
```

File: client/src/ui/organisms/product-features/index.tsx [hunk 17]
```diff
@@ -0,0 +1,42 @@
+import "./index.scss";
+
+const ProductFeatures = ({ withIntro }) => {
```
Comment (peterbe) [inline client/src/ui/organisms/product-features/index.tsx:3]: ditto

**Review by peterbe — COMMENTED** [review]
It's hard to review this because of the current situation and context. I don't know important it is that the code isn't "as good as it could be". Perhaps it's just a quick hacky draft meant to be improved or perhaps it's meant to go into `main` with a follow-up to fix later. 

It works and it displays deep-dives and perhaps that's the important thing given the time constraints. You'll have to guide me with reviewing. At the time of writing, unfortunately, you're offline @schalkneethling so I just jotted down some more or less nits. 

Once we get the basics right I can get cracking on rewriting the `<Survey>` component so it fully works and works with Kuma.

File: client/src/deep-dive/your-browser-support-toolkit.tsx (hunk 1 above)
Comment (schalkneethling) [reply client/src/deep-dive/your-browser-support-toolkit.tsx]: Yup, waiting for Daryl/Hermina.

File: client/src/plus/app.tsx (hunk 10 above)
Comment (schalkneethling) [reply client/src/plus/app.tsx:1]: Yup, it is because we are overriding some fonts. It is going to be a total hack to address it so, I reckon it is ok for the duration of the experiment and only affects these pages.
