### PR TITLE
enhance(play): log empty array values as `<1 empty slot>` / `<2 empty slots>`

### LINKED ISSUE #12943: wrong example o/p for Remove array element with Reflect.deleteProperty()
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/deleteProperty

### What specific section or headline is this issue about?

Try it code example, console logs `undefined` instead of `empty slot`. 

### What information was incorrect, unhelpful, or incomplete?

Image

Also, [Using Reflect.deleteProperty()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/deleteProperty#using_reflect.deleteproperty) shows wrong o/p.

### What did you expect to see?

Try it example console should return `empty`.
Also correct [Using Reflect.deleteProperty()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/deleteProperty#using_reflect.deleteproperty)

### Do you have any supporting links, references, or citations?

see [delete operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete#deleting_array_elements). 

### Do you have anything more you want to share?

Chrome and ff create `empty` space on array element deletion.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/reflect/deleteproperty`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/deleteProperty
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/reflect/deleteproperty/index.md
* Last commit: https://github.com/mdn/content/commit/2982fcbb31c65f324a80fd9cec516a81d4793cd4
* Document last modified: 2025-02-11T14:16:45.000Z

</details>

### PR DESCRIPTION
**Pull request by caugner**
## Summary

Fixes https://github.com/mdn/yari/issues/12943.

### Problem

The Playground console formatted empty slots in arrays as `undefined`.

### Solution

Format these as `<1 empty slot>` or `<2 empty slots>` instead.

---

## Screenshots

| Before | After |
|--------|--------|
| image | image | 
| image | image |

---

## How did you test this change?

Ran `yarn dev` and compared http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/deleteProperty#try_it to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/deleteProperty#try_it.

### CODE REVIEW

File: client/src/lit/play/console-utils.js [hunk 1]
```diff
@@ -17,6 +18,17 @@ export function formatArray(input) {
...
       output += formatArray(input[i]);
       output += "]";
+    } else if (!input.hasOwnProperty(i)) {
+      let emptyCount = 1;
+      while (i + 1 < l && !input.hasOwnProperty(i + 1)) {
+        emptyCount++;
+        i++;
+      }
+      if (emptyCount === 1) {
+        output += "<empty>";
```
Comment (LeoMcA) [inline client/src/lit/play/console-utils.js:28]: I would follow Firefox's formatting of `<1 empty slot>` here

**Review by LeoMcA — APPROVED** [review]

File: client/src/lit/play/console-utils.js (hunk 1 above)
Comment (ShubhamOulkar) [inline client/src/lit/play/console-utils.js:28]:
```suggestion
        output += "<${emptyCount} empty slot>";
```
Empty slot is shown as `<1 empty slot>` in Firefox.

Comment (ShubhamOulkar) [reply client/src/lit/play/console-utils.js:28]: Oops... @LeoMcA suggested same formatting.

Comment (caugner) [reply client/src/lit/play/console-utils.js]: Fixed via b5ac744385.

**Comment by caugner** [comment]
Thanks @ShubhamOulkar, good catch!
