### PR TITLE
fix: updates deep dive article content

### LINKED ISSUE #4318: Deep dive article content updates
Ensure the two deep-dive articles have the latest content updates as per the doc on drive.

### PR DESCRIPTION
**Pull request by schalkneethling**
Updates to article content for deep dives

fix #4318

### CODE REVIEW

File: client/src/plus/deep-dives/sample-articles.tsx [hunk 1]
```diff
@@ -159,7 +161,7 @@ export function PlanningForBrowserSupport() {
       <p>
         Make sure that, before you begin to plan your support strategy, you are
         all talking about the same thing when you talk about{" "}
-        <strong>supporting a browser</strong>.
+        <strong>supporting a browser.</strong>
```
Comment (dalexsy) [inline client/src/plus/deep-dives/sample-articles.tsx:164]: Punctuation goes outside of styling, so the period shouldn't be bolded. I asked Ruth about this because it's on a case by case basis, and she says MDN will not style punctuation.

File: client/src/plus/deep-dives/sample-articles.tsx [hunk 2]
```diff
@@ -238,6 +240,13 @@ export function PlanningForBrowserSupport() {
         many are on mobile devices, and which versions of evergreen browsers
         that are in use.
       </p>
+      <figure>
+        <img src="" width="" height="" alt="" />
```
Comment (dalexsy) [inline client/src/plus/deep-dives/sample-articles.tsx:244]: Here's the image: https://drive.google.com/file/d/12DihQAsu-_nBaTQRUlwGWD_RfEGnTQ9d/view?usp=sharing

File: client/src/plus/deep-dives/sample-articles.tsx [hunk 3]
```diff
@@ -396,7 +397,7 @@ export function YourBrowserSupportToolkit() {
       </header>
       <p className="article-lead">
         In this article discover the resources available, to help you develop a
-        site that will perform well across browsers and devices
+        site that will perform well across browsers and devices.
```
Comment (dalexsy) [inline client/src/plus/deep-dives/sample-articles.tsx:400]: We're not using periods at the end of the article lead, so no period was correct.

File: client/src/plus/deep-dives/sample-articles.tsx [hunk 4]
```diff
@@ -951,8 +957,12 @@ export function YourBrowserSupportToolkit() {
         useful tool if you get a bug report on your site from an unusual or
         particularly old browser that you do not have access to.
       </p>
+      <figure>
+        <img src="" width="" height="" alt="" />
```
Comment (dalexsy) [inline client/src/plus/deep-dives/sample-articles.tsx:961]: Image is here: https://drive.google.com/file/d/1r2E2o93Rz7NXqb-FgTzHEPBLDVXsRRo4/view?usp=sharing

File: client/src/plus/deep-dives/sample-articles.tsx [hunk 5]
```diff
@@ -752,31 +753,36 @@ export function YourBrowserSupportToolkit() {
...
-          79, almost all iOS browsers including Firefox for iOS, any other
-          Chromium-based browsers not already mentioned — including Brave,
-          Samsung Internet, etc.)
+          <code>-webkit-</code> (Chrome, Safari, newer versions of Opera, Edge
+          after version 79, almost all iOS browsers including Firefox for iOS,
+          any other Chromium-based browsers not already mentioned &mdash;
+          including Brave, Samsung Internet, etc.)
+        </li>
+        <li>
+          <code>-moz-</code> (Firefox)
```
Comment (dalexsy) [inline client/src/plus/deep-dives/sample-articles.tsx:770]: The code background color doesn't read well against the background, could you change the code background to light grey 30 (#E0E0E6) at 50%?

**Review by dalexsy — COMMENTED** [review]
Added links to graphics and stylistic changes

File: client/src/plus/deep-dives/overview/index.scss [hunk 6]
```diff
@@ -0,0 +1,204 @@
...
+        margin: layout.$base-spacing 0;
+      }
+    }
+
+    h2 {
+      background: theme.$gradient-accent;
+      background-clip: text;
+      color: theme.$mdn-green400;
+      font-size: typography.$medium-font-size;
+      margin-top: 0;
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:80]: Would change font size and add ```font-size: 18px;
    line-height: 160%;
    text-transform: uppercase;```

File: client/src/plus/deep-dives/overview/index.scss [hunk 7]
```diff
@@ -0,0 +1,204 @@
...
+      height: 529px;
+    }
+  }
+
+  .header-wrapper {
+    background-color: rgba(0, 0, 0, 0.4);
+    height: 100%;
+    margin: auto;
+    max-width: layout.$max-width-default;
+    padding: (layout.$base-spacing * 2) layout.$base-spacing;
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:42]: Would change to `padding: 120px;` so it aligns with the text below

File: client/src/plus/deep-dives/overview/index.scss [hunk 8]
```diff
@@ -0,0 +1,204 @@
...
+}
+
+.overview-hero {
+  color: theme.$text-color-inverted;
+  overflow: hidden;
+  padding: 0;
+  position: relative;
+
+  @media #{layout.$mq-large-desktop-and-up} {
+    padding: 0 0 (layout.$base-spacing * 2.5);
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:20]: Would remove this

File: client/src/plus/deep-dives/overview/index.scss [hunk 9]
```diff
@@ -0,0 +1,204 @@
...
+      }
+    }
+  }
+}
+
+.overview-content-container {
+  padding: math.div(layout.$base-spacing, 2) layout.$base-spacing;
+
+  @media #{layout.$mq-small-desktop-and-up} {
+    padding: layout.$base-spacing 120px;
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:111]: Would remove top padding and change to `padding: 0px 120px 36px;`. The margin from the header should do the spacing.

File: client/src/plus/deep-dives/overview/index.scss [hunk 10]
```diff
@@ -0,0 +1,204 @@
...
+
+  h3,
+  h4 {
+    font-size: typography.$small-medium-font-size;
+    margin: layout.$base-spacing 0;
+  }
+
+  h4 {
+    font-size: typography.$default-font-size;
+    margin: math.div(layout.$base-spacing, 2) 0;
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:127]: Would change this to `margin: 36px 0;`

File: client/src/plus/deep-dives/overview/index.scss [hunk 11]
```diff
@@ -0,0 +1,204 @@
...
+    background: transparent url("./assets/hero.svg") center center no-repeat;
+    background-size: cover;
+    content: "";
+    display: block;
+    min-height: 365px;
+    position: absolute;
+    width: 100%;
+
+    @media #{layout.$mq-small-desktop-and-up} {
+      height: 529px;
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:33]: Change to `height: 100%;`

File: client/src/plus/deep-dives/overview/index.scss [hunk 12]
```diff
@@ -0,0 +1,204 @@
...
+
+  li {
+    margin-bottom: layout.$base-spacing;
+  }
+
+  a.overview-series-list-item {
+    border-radius: 4px;
+    display: block;
+    min-height: 140px;
+    padding: math.div(layout.$base-spacing, 4);
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:138]: I wanted this to be 12px instead of 6px, but weird things happen when I change it. It's not critical, but I wanted to have the links with no margins between them, like the spacing would just come from the padding. If it's too complicated, we can leave it.

File: client/src/plus/deep-dives/overview/index.scss [hunk 13]
```diff
@@ -0,0 +1,204 @@
...
+  }
+
+  .your-browser-support-toolkit {
+    &::before {
+      background: transparent url("./assets/your-browser-support-toolkit.svg")
+        center center no-repeat;
+    }
+  }
+
+  .unavailable {
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:189]: This needs the same padding the other list items have.

File: client/src/plus/deep-dives/overview/index.scss (hunk 10 above)
Comment (dalexsy) [reply client/src/plus/deep-dives/overview/index.scss:127]: Should also be `font-size: 18px;` instead of 20px

File: client/src/plus/deep-dives/overview/index.scss [hunk 14]
```diff
@@ -0,0 +1,204 @@
...
+
+      @media #{layout.$mq-small-desktop-and-up} {
+        font-size: typography.$small-medium-font-size;
+      }
+    }
+  }
+}
+
+.overview-content-container {
+  padding: math.div(layout.$base-spacing, 2) layout.$base-spacing;
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:108]: Would remove top padding and change to `padding: 0px 120px 36px;`. The margin from the header should do the spacing.

File: client/src/plus/deep-dives/overview/index.scss [hunk 15]
```diff
@@ -0,0 +1,204 @@
...
+    position: absolute;
+    width: 100%;
+
+    @media #{layout.$mq-small-desktop-and-up} {
+      height: 529px;
+    }
+  }
+
+  .header-wrapper {
+    background-color: rgba(0, 0, 0, 0.4);
```
[the remark this answers is not in the document]
Comment (schalkneethling) [reply client/src/plus/deep-dives/overview/index.scss:38]: Doh! fixed :)

File: client/src/plus/deep-dives/overview/index.scss [hunk 16]
```diff
@@ -0,0 +1,204 @@
...
+    &:focus {
+      background-color: theme.$mdn-neutral100;
+      text-decoration: none;
+    }
+
+    &::before {
+      background-size: cover;
+      content: "";
+      display: inline-block;
+      height: 128px;
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:156]: Change this to `height: calc(100vw * 0.6);
    width: 100%;` for mobile

File: client/src/plus/deep-dives/overview/index.scss [hunk 17]
```diff
@@ -0,0 +1,204 @@
...
+      background: transparent url("./assets/your-browser-support-toolkit.svg")
+        center center no-repeat;
+    }
+  }
+
+  .unavailable {
+    &::before {
+      background: transparent url("./assets/unavailable.svg") center center
+        no-repeat;
+      background-size: 164px 129px;
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:188]: Change to `background-size: 100%;
    content: "";
    display: inline-block;
    height: calc(100vw * 0.6);
    width: 100%;
    border-radius: 4px;` for mobile

File: client/src/plus/deep-dives/overview/index.scss [hunk 18]
```diff
@@ -0,0 +1,204 @@
...
+  }
+
+  &::before {
+    background: transparent url("./assets/hero.svg") center center no-repeat;
+    background-size: cover;
+    content: "";
+    display: block;
+    min-height: 365px;
+    position: absolute;
+    width: 100%;
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/index.scss:26]: Add `height:100%` for mobile

File: client/src/plus/deep-dives/overview/app.tsx [hunk 19]
```diff
@@ -0,0 +1,105 @@
...
+                  Learn about the types of CSS issues you'll be facing when
+                  working with your team in a web-based environment and tips for
+                  developing a future-proof support strategy
+                </p>
+              </div>
+            </a>
+          </li>
+          <li>
+            <a
+              href={`/${locale}/plus/deep-dives/planning-for-browser-support`}
```
Comment (dalexsy) [inline client/src/plus/deep-dives/overview/app.tsx:78]: Link is wrong

File: client/src/plus/deep-dives/overview/index.scss (hunk 10 above)
Comment (dalexsy) [reply client/src/plus/deep-dives/overview/index.scss]: Sorry, margin: `margin: 36px 0;` for h3 only

**Review by dalexsy — COMMENTED** [review]
Reviewed stylistic changes for overview page
