### PR TITLE
contributors URL's are incorrectly considered broken

### LINKED ISSUE #3446: contributors URL's are incorrectly considered broken
image

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #3446

### CODE REVIEW

**Comment by peterbe** [comment]
Easy to test by viewing http://localhost:3000/en-US/docs/MDN/About#_flaws before and after.

File: build/flaws/broken-links.js [hunk 1]
```diff
@@ -164,6 +164,11 @@ function getBrokenLinksFlaws(doc, $, { rawContent }, level) {
           "Link points to the page it's already on"
         );
       }
+    } else if (
+      hrefNormalized.endsWith("/contributors.txt") &&
+      hrefNormalized.startsWith("/")
+    ) {
+      // Do nothing. The /contributors.txt URLs are special Yari URLs.
```
Comment (escattone) [inline build/flaws/broken-links.js:171]: @peterbe What do you think about moving these "do nothing" cases above this long "do something" `if-else` statement? So maybe right after we create and define the `hrefNormalized` variable near the top of this loop function, we do something like the following that we can add more cases to over time?

```js
if (
      hrefNormalized.endsWith("/contributors.txt") &&
      hrefNormalized.startsWith("/")
    ) {
  return;
}
```

**Review by escattone — APPROVED** [review]
Nice, thank you @peterbe!
