### PR TITLE
fix:ux-a11y - a proposal for improving the readibility and accessibil…

### LINKED ISSUE #5369: UI suggestion: Make index list 'headings' easier to recognize
Looking at this alphabetical list of all the APIs that are available, it is difficult for me to find the correct letter 'heading'.

**Example:**
https://developer.mozilla.org/en-US/docs/Web/API#specifications

**Possible enhancement:**
Screenshot of the lengthy Web APIs index on MDN. The list is alphabetically organized, with headers for each letter ("A", "B", "C"). The screenshot includes a style modification to more strongly visually indicate  these headers.

### LINKED ISSUE #5372: Font-size on the front page is too small
16px is generally recommended size, and it's what other MDN pages that I just looked at have.

It's 13px on the front page, and it's too small to be legible.

### LINKED ISSUE #5377: Bug: Paragraphs have too much line height
# Summary

In the redesigned MDN docs, it's difficult to distinguish paragraphs from other surrounding text (and from each other).

## Where did you spot the bug?

A good content-heavy page: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

image

## What is the problem?

The paragraphs have too much line height compared to the spacing between them, making them visually blend into each other.

## What did you expect to happen?

The paragraphs should use a line height that improves readability and makes it easier for readers to distinguish paragraphs from each other. From testing, the following values seem to work well:

- Line height: `1.8`
- Paragraph spacing: `1.8rem 0`

Example:

image

## Steps to reproduce the issue

1. Visit any page in the new docs.
2. Observe that too much line height is being used for text.

## Environment

Any (N/A)

### Device

- [x] Desktop
- [x] Mobile
- [x] Tablet

### Browser

Any

### Operating system

Any

### LINKED ISSUE #5378: Dark mode a little too contrasty
# Summary

Thanks for the new dark mode option! 🖤 My only feedback is that it might be a bit *too* dark: so much contrast with the white text can make it hard to read. I have slight astigmatism, so it might be that; I've heard it's a common problem.

I gave the same feedback to GitHub when they released their dark mode; they later released a "dim" mode with a slightly lighter background, and it helped a lot. The TypeScript docs site is another good example of an easier contrast, and so is the dark mode on MacOS.

Other than this I'm jazzed for the redesign, and happy to see great work go into a site I use and learn from every day. Cheers!

### LINKED ISSUE #5387: New dark design is striking but dark blue is nearly invisible on black background
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback

#### What information was incorrect, unhelpful, or incomplete?

New dark design is striking but dark blue is nearly invisible on black background!

#### Specific section or headline?

This combination appears in multiple places, including this page.

#### What did you expect to see?

Text.

#### Did you test this? If so, how?

Just reporting state of my old eyeballs. Something for RFE list if others agree.

In case this bug report is not reporting page I was on, see (for example) top of this page,

https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings

thx.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/feedback`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/feedback/index.md
* Last commit: https://github.com/mdn/content/commit/072ff0c2bdfa29c02861450b6a91ff93f46e2218
* Document last modified: 2022-02-18T09:11:14.000Z

</details>

### LINKED ISSUE #5389: Whitespace, Header styling, code background contrast, remove 3rd column, etc
I'm adding CSS styles here for people who need to use this site for work and get things done: less whitespace, better headers, full screen width, sidebar element spacing, code background contrast, scrollbar styling, always open search input, sticky top headers, darker dark mode, and other misc. updates: use extension like [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en) to add styles

<details>
  <summary>Click to expand CSS styles</summary>

```css
h1, h2, h3, h4 {
    margin: .75rem 0 !important;
}
h1, h2 {
    font-weight: bold;
}
h2 {
    font-size: 1.6rem;
}
h3 {
    font-size: 1.25rem;
    font-weight: 600;
    margin-left: 1rem !important;
}
p {
    padding-left: 1rem;
    line-height: 150% !important;
    margin: .75rem 0 !important;
}
a {
    padding: 0 !important;
}
a > code { 
    color: var(--text-link);
}
pre {
    padding: 0.45rem 0.7rem;
    margin: 0.75rem 0.5rem 0.5rem 1rem;
}
code {
    background: hsl(240deg 10% 95%);
}
pre {
    background: hsl(240deg 10% 96%);
}
.dark code {
    background: hsl(247deg 10% 20%);
}
.dark pre {
    background: hsl(247deg 10% 10%);
}
pre code {
    background: none !important;
}
body #sidebar-quicklinks code {
    background: none;
}
body.dark {
    background: #000 !important;
}
#content {
    padding: 0 .5rem 0 .75rem;
    box-shadow: -5px 0 5px -5px #888;
    overflow-x: hidden;
}
.logo svg {
   margin-top: 0;
}
.article-wrapper .main-content, .article-wrapper .sidebar, .article-wrapper .toc{
    padding-top: 0;
    padding-bottom: 0;
}
.article-wrapper {
    padding-left: 0.5rem;
    padding-right: 0rem;
}
.article-wrapper {
    gap: 0rem;
}
.article-actions-container {
    position: sticky;
    top: 33px;
    z-index: 99;
}
.dark .article-actions-container {
    background: #000000;
}
.top-navigation {
    position: sticky;
    top: 0;
}
.dark .top-navigation {
    background: #000000;
}
#sidebar-quicklinks {
    top: 65px;
    max-height: calc(100vh - 65px);
    overflow-x: hidden;
}
.main-page-content dl dt {
    margin-top: .5rem;
}
.sidebar li, .sidebar summary {
    margin-bottom: 0rem;
}
.sidebar li strong {
    margin: 0.5rem 0;
}
.sidebar li details {
    margin: 0;
}
.sidebar details ol {
    margin: 0.25rem 0.5rem;
    padding-left: 0.75rem;
}
.article-wrapper {
     max-width: unset;
}
.document-toc-list.document-toc-list li {
    margin: 2px 0;
}
.document-toc {
    margin-bottom: 0rem;
}
.document-toc-link.document-toc-link:not(.button) {
    padding: 0 0 0 .5rem !important;
}
.toc {
    display: none !important;
}
.main-page-content ol li, .main-page-content ul li {
    margin: 0.25rem 0;
    line-height: 150%;
}
.main-page-content ol, .main-page-content ul {
    margin: 0.5rem 0 0.5rem;
}
.main-page-content dl dt {
    margin-left: 1rem;
    margin-top: 0.5rem;
}
.main-page-content a:link, .main-page-content a:visited {
    text-decoration: none;
}
.main-page-content a:hover {
    text-decoration: underline;
}
.container {
    max-width: 100%;
}
.callout {
    padding: 0rem;
    gap: 0;
    margin: 1rem 0;
    text-align: center;
}
.breadcrumb:hover span, .breadcrumb-current-page:hover span {
    text-decoration: underline;
}
.close-search-button {
    display: none;
}
.search-button {
    display: none;
}
.top-navigation-main .header-search {
    max-width: 280px;
}
#top-nav-search-q {
    height: 28px;
    padding: 0 10px;
    margin: 2px 0px;
}
.switch .slider {
    background-color: var(--text-link);
}
.dark .switch .slider {
    background-color: var(--text-secondary) !important;
}
.mdn-cta-container, .auth-container {
    display: none;
}
@media screen and (min-width: 769px) {
    .article-wrapper {
        grid-template-columns: min(250px, 20%) 1fr;
    }
    .breadcrumbs-container li {
        display: inline-flex !important;
    }
    .top-navigation-main .search-form {
        display: block;
    }
    .top-navigation-main .toggle-search-button {
        display: none;
    }
}
@media screen and (min-width: 1200px) {
    .article-wrapper {
        grid-template-columns: min(250px, 20%) 1fr;
        grid-template-areas: "sidebar main";
    }
    .article-wrapper .in-nav-toc {
        display: block;
    }
}
:root {
    --top-nav-height: 1rem;
}
:target {
    scroll-margin-top: 70px;
}
::-webkit-scrollbar {
    width: 10px;
    height: 6px;
}
body ::-webkit-scrollbar-thumb {
    background: #ccc;
}
body ::-webkit-scrollbar-track {
    background: #eee;
}
.dark ::-webkit-scrollbar-track {
    background: hsl(0deg 0% 5%);
}
.dark ::-webkit-scrollbar-thumb {
    background: hsl(0deg 0% 15%);
}
```

</details>

# Before:

image

# After:

image

# Before:

image

# After:

image

### LINKED ISSUE #5396: Colour contrast is so low, some colours are impossible to see
From the page: <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog>:

_dialog___The_Dialog_element_-_HTML__HyperText_Markup_Language___MDN

### LINKED ISSUE #5415: Bug: Line heights for Chinese is content is very compact
# Summary

From Twitter:
https://twitter.com/createthink_net/status/1498685146916352000/photo/1

## Where did you spot the bug?

Reference pages in the Chinese language

## What is the problem?

Need greater line-height for the Chinese language readers

Screenshot 2022-03-02 at 14 43 20

### LINKED ISSUE #5430: Regression: Missing links are no longer highlighted properly
# Summary

The theme color for links is currently overriding the error color for links that don't have a destination. This is doubly true for any links that also have a `code` block inside them.

## Where did you spot the bug?

https://developer.mozilla.org/en-US/docs/Web/API/FileReader#event_handlers

The last three should have red text, or at least text of a different color showing that the link deistinations don't exist. 

"Fixed" version

## What is the problem?

There's no way to tell if a link exists or not until you hover and try to click it.

(this is even more of an issue on the HTML doc pages because the theme color is already red but that's been discussed in #5367)

## What did you expect to happen?

These links should be highlighted like they used to be. It seems like the CSS is still there to support it but the cascading/specificity of the CSS is overwriting it. Even if you fix the first issue I also noticed that `code` blocks inside `.page-not-created` links once again force the theme color.

I fixed this by adding:

```css
a.page-not-created {
  color: var(--icon-critical) !important;
}
a.page-not-created code {
  color: var(--icon-critical);
}
```

### LINKED ISSUE #5445: Bug: Links are not clearly differentiated
# Summary

Links are not clearly differentiated from other elements (headings, body text). Sometimes they look identical to other elements (headings) sometimes they have a colour variation.

Sometimes links are obvious from their context (say a browse menu) but otherwise the most accessible way to differentiate links from surrounding elements is to use an underline.

### LINKED ISSUE #5485: Bug: H2 and H3 headings are not visually distinct
In the redesign, H2 and H3 headings look really similar. In the reference docs we rely heavily on H2 headings to communicate top-level structure (Description/Syntax/Specifications/Browser compatibility) to readers, and having it non-obvious whether something is an H2 or an H3 makes this difficult.

Screen Shot 2022-03-04 at 4 23 19 PM

### LINKED ISSUE #5521: UI suggestion: Make header and breadcrumbs sticky
# Summary

MDN header (with search button) and breadcrumbs (with language selector) can be scrolled away.

## Where did you spot the bug?

[](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

## What is the problem?

It is quite inconvenient to browse MDN page, then decide to find something else and not having search box anywhere on screen because the page was scrolled down.

## What did you expect to happen?

Search box must be one click away all the time.

### Browser

- [ ] Chrome: (what version?)
- [x] Firefox: 99
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [x] Windows: 10
- [ ] Mac OS: (what version?)
- [ ] Linux: (what distribution / version?)

## Screenshots

image

### LINKED ISSUE #5546: Research: Readability and accessibility of main content
This issue is to track the work we are doing to rethink the typography and colors used for the main content of our documents across technologies and the learning area. The issue will be fleshed out as the work progresses.

## Related remarks

- [x] On the HTML pages in dark mode, links containing <code> almost look like red underlines for grammatical errors
- [x] Would it be possible to add icons for the browsers in the Browser Compatibility tables?
- [x] Return background color to active TOC entries
- [x] Reduce weight of h1
- [x] Smaller font scale for mobile
- [x] Move notes and related icons to below version number 

## Related issues

- [x] #5378
- [x] #5387
- [x] #5396
- [x] #5389
- [x] #5377
- [x] #5415
- [x] #5430
- [x] #5445
- [ ] #5468
- [ ] #5469
- [x] #5485
- [x] #5372
- [x] #5569
- [x] #5596
- [x] #5632
- [x] #5666
- [x] #5755
- [x] #5521
- [ ] Feedback from the community: https://twitter.com/ferdnyc/status/1508384644475068420
- [ ] #5878
- [x] #5906
- [x] #5914
- [x] #5919
- [x] #5521
- [x] #5934
- [x] #5831
- [x] #5369

### LINKED ISSUE #5569: Links within code are greyish and hard to read, different than normal links
### Summary

Links inside code are colored different than other links. These are a little harder to read due to being greyish color inside an already grey code block, but mostly it just does not look like a link because the color is off. It would look better and make more sense to have those the same color text as other links

 Ref: https://github.com/mdn/yari/issues/5445

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects

### Reproduction steps

1. Look at page

### Expected behavior

Code Links same color as normal links

### Actual behavior

Code links different color, harder to read, confusing meaning

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

# Before

chrome_40e1bqKa7K

# After

5NnkOu5u60

# Before

image

# After

image

### Anything else?

_No response_

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### LINKED ISSUE #5596: Header and Nav links use "16px" instead of "1rem", look small with large browser font-size
### Summary

Nav links use "16px" instead of "1rem", look small with large browser font-size

### URL

https://developer.mozilla.org/en-US/docs/Learn/CSS

### Reproduction steps

Increase the browser font-size

### Expected behavior

All font size on site increases 

### Actual behavior

All font size increase except the Header and Breadcrumb nav links

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

# Current:
gsKMVMPUle

# Fixed:
chrome_jH6mkGBoP8

### Anything else?

_No response_

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### LINKED ISSUE #5632: Pages like Web APIs with multiple columns look bad on mobile
### Summary

To clarify, "bad" is just a succinct word to use in the title. Hard work went into the docs and this is appreciated. I love front end devs. Please don't make me center a div. <3

On mobile, pages like https://developer.mozilla.org/en-US/docs/Web/API look bad because the three columns cause the content to get squished too much and cause text in one column to get cut off as you scroll down.

I think it would look better if it was just one column on mobile.

This may affect other pages on the site too. I haven't checked other areas yet.

### URL

https://developer.mozilla.org/en-US/docs/Web/API

### Reproduction steps

1. In a phone's mobile browser (I used Firefox on Android) go to https://developer.mozilla.org/en-US/docs/Web/API
2. Scroll down
3. Observe content

### Expected behavior

Content is in a form easy to read

### Actual behavior

Content is possibly hard to read

### Device

Smartphone

### Browser

Firefox

### Browser version

Stable

### Operating system

Android

### Screenshot

https://pbs.twimg.com/media/FN5GredWYAUI6mV?format=jpg&name=900x900

### Anything else?

from https://twitter.com/schalkneethling/status/1503779679811121153

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### LINKED ISSUE #5666: Dark mode: weird white spot with both scrollbars
### Summary

In dark theme there is a small white box where two scrollbars meet:

### URL

https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

### Reproduction steps

1. Open url https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
2. Go all the way to the bottom of the page.
3. Notice the white spot.
4. If there is no horizontal scroll on the navLink section then reduce width of the browser window or zoom or adjust zoom.

### Expected behavior

No white spot be seen. 
If there is no proper way then may be we can use black `::after` pseudo element to cover the spot.

### Actual behavior

There is a white spot.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

_No response_

### Anything else?

_No response_

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### LINKED ISSUE #5755: Consider not having different link colors for different site areas
I haven't seen this reported anywhere else, so maybe it's an unpopular opinion, but I think MDN should not have different link colors for different areas of the site.

I do understand the desire to indicate that we are in "the CSS docs" with some accent color, but link colors are tricky to get right: we have to care about contrast, conventional expectations, not-found links (and conventional expectations about them), contrast against `<code>` formatting. And then do all that for both themes. Then having to do that for every bit of the site makes it really hard to get good colors.

I think it's also possibly confusing for users, who probably see MDN as a single site, to see different link colors on different pages.

### LINKED ISSUE #5831: Big vertical margins, especially with "try it" heading
In pages with interactive examples, we now have a lot of whitespace at the top of the page:

Screen Shot 2022-03-27 at 11 12 24 AM

...it would be better with less:

Screen Shot 2022-03-27 at 11 13 06 AM

### LINKED ISSUE #5906: Color of dead links: contrast issue
### Summary

When a page isn't written yet, the link is red based on the class `.page-not-yet-written`.
The HTML section has red links.
The specificity of those links overrides the colors based on it not yet being written.
There isn't enough differentiation between the two reds to see that the "not yet written" links are, well, not yet written, if those links got the right red.

### URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/max

### Reproduction steps

1. visit https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/max
2. in the see also section, `low`, `optimimum` and `high` are dead links. 
3. 

### Expected behavior

links with the class `.page-not-yet-written` should be a different color from other links

### Actual behavior

they're all the same color

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

_No response_

### Anything else?

this could be solved with a more specific select.

```css
a.page-not-yet-written.page-not-yet-written.page-not-yet-written {
/* this has a specificity of 0-3-1 */
}
```

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### LINKED ISSUE #5914: Empty placeholder attribute on search input
### Summary

The search input elements have an empty `placeholder` attribute. While it might not be the end of the world, probably better to not have the attribute at all.

### URL

https://developer.mozilla.org/

### Reproduction steps

See summary

### Expected behavior

There is no `placeholder` attribute on search input fields.

### Actual behavior

See summary

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

_No response_

### Anything else?

_No response_

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### LINKED ISSUE #5919: Add skip to search link in a11y-nav
### Summary

We used to have a "skip to search" link as part of the a11y-nav. I believe it was temporarily removed. We should add the link again now that I think the affected pieces are stable.

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

### Reproduction steps

Open the above page and press the tab key. Links to the main content and language selector are available. It is missing a link to search.

### Expected behavior

a11y-nav should also contain a link to skip to search.

### Actual behavior

See "Reproduction steps"

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

_No response_

### Anything else?

_No response_

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### LINKED ISSUE #5934: Issue with all SVG docs: links with missing content look normal
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SVGElement

(Actually, this applies to all SVG docs on MDN.)

#### What information was incorrect, unhelpful, or incomplete?

The SVG docs are—compared to the docs for HTML, CSS, and Javascript—largely incomplete.  

Since MDN’s recent redesign, there are dozens and dozens of links that look like they will show me the appropriate documentation if I click on them...until, that is, my cursor moves over the link!  The 🚫 symbol appears, and _then_ a tooltip tells me that the article is not yet written.

#### Specific section or headline?

Many links throughout the SVG docs.

#### What did you expect to see?

Links to unwritten articles used to be styled differently, so that it was possible to identify them without moving your mouse over them.

The hover cursor 🚫 and the tooltip are fine.  I just want to be able to _spot_ those links without having to mouse over each one (or keep track of them in my head; there are so many incomplete SVG articles, and I kept trying to explore different pages, only to find link after link that doesn’t work).

#### Did you test this? If so, how?

See above.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/svgelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SVGElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/svgelement/index.md
* Last commit: https://github.com/mdn/content/commit/93ae23dec42bba9d71d6f1ed45668d8d26847e9c
* Document last modified: 2022-02-18T09:26:54.000Z

</details>

### PR DESCRIPTION
**Pull request by schalkneethling**
This PR improves the readability and accessibility of the MDN Web Docs, based on feedback that we have received.

fix #5546
fix #5378
fix #5387
fix #5396
fix #5389
fix #5377
fix #5415
fix #5430
fix #5445
fix #5485
fix #5372
fix #5569
fix #5596
fix #5632
fix #5666
fix #5755
fix #5521
fix #5906
fix #5914
fix #5919
fix #5521
fix #5934
fix #5831
fix #5369

### a11y

- Adjust colors, font-sizes, font-weights and spacing for readability.
- Underline links.
- Make top navigation sticky on desktop.
- Use default caret for prefers-reduced-motion. 
- Re-enable skip to search.
- Replace notes symbol in BCD table.

### Chores

- Improve CSS variable structure.
- Define base font-size and line-height.
- Build contributor-spotlight in dev-build.
- Remove scrollbar customisations.
- Extract common `<Menu> `component.
- Replace `<em>` with `<strong>` in macros.
- Use `<summary>` in JSRef macro.
- Use `<h3>` in APIListAlpha and ListGroups macros.

### CODE REVIEW

**Comment by caugner** [comment]
@schalkneethling When I click on a TOC item, the heading is hidden behind the sticky header. Did you have some unpushed commits, by any chance?

Best would be to tag the sticky items (desktop and mobile have different ones, argh) with a `.sticky-header` CSS class. Then I can use a `ResizeObserver` to observe its height, and set the rootMargin of the `IntersectionObserver` accordingly.

**Comment by schalkneethling** [comment]
> @schalkneethling When I click on a TOC item, the heading is hidden behind the sticky header. Did you have some unpushed commits, by any chance?
> 
> image
> 
> Best would be to tag the sticky items (desktop and mobile have different ones, argh) with a `.sticky-header` CSS class. Then I can use a `ResizeObserver` to observe its height, and set the rootMargin of the `IntersectionObserver` accordingly.

Just pushed the latest. Feel free too refactor to better suit your needs with the `IntersectionObserver` if need be. Let me know once you have pushed your updates. Thanks, @caugner!

**Review by caugner — COMMENTED** [review]
When the sticky header is visible, the "Related Topics" heading in the left sidebar and the "In this article" heading in the right sidebar are hidden by the sticky header.

File: client/src/ui/molecules/guides-menu/index.tsx [hunk 1]
```diff
@@ -88,7 +89,7 @@ export const GuidesMenu = ({ visibleSubMenuId, toggleMenu }) => {
         Guides
       </InternalLink>
 
-      <Submenu menuEntry={menu} defaultHidden={!isOpen} />
+      <Submenu submenuId={menu.id} menuEntry={menu} defaultHidden={!isOpen} />
```
Comment (caugner) [inline client/src/ui/molecules/guides-menu/index.tsx:92]: This results in `<ul id="guides" ...>` and breaks the `#guides` TOC entry on [this page](http://localhost:3000/en-US/docs/Learn/HTML/Introduction_to_HTML#guides).

```suggestion
      <Submenu submenuId={`${menu.id}-menu`} menuEntry={menu} defaultHidden={!isOpen} />
```
(Also needs to updated in the `aria-controls` above.

**Comment by caugner** [comment]
@schalkneethling I have now pushed the TOC fix in 9d5c3daa3b36b9fa11193c19cb3380e72990bdb9.

File: client/src/ui/molecules/guides-menu/index.tsx (hunk 1 above)
Comment (caugner) [reply client/src/ui/molecules/guides-menu/index.tsx:92]: 👀 I will push a fix in a second.

Comment (caugner) [reply client/src/ui/molecules/guides-menu/index.tsx]: ✅ Resolved as follows:

1. Extracted a common `<Menu>` component for the Reference/Guides/Plus menu.
2. Added a `-menu` suffix to the id.

Comment (caugner) [reply client/src/ui/molecules/guides-menu/index.tsx]: ^ FYI @schalkneethling

**Comment by schalkneethling** [comment]
> @schalkneethling I have now pushed the TOC fix in [9d5c3da](https://github.com/mdn/yari/commit/9d5c3daa3b36b9fa11193c19cb3380e72990bdb9).

Thanks so much @caugner!

**Comment by schalkneethling** [comment]
Hey @caugner,

The pull request is ready for review, but it is massive, to be honest. I am happy for you all to decide how to handle merging this. Just a couple of points to keep in mind.

1. This _needs_ to go out on Wednesday morning along with a post on the Hacks blog
2. You can merge this as is and then iterate with follow up pull requests
3. You could do a complete review of this pull request. If you choose to do this and find something you would have done differently, I would say push updates to address these instances.

Thank you.

File: client/src/homepage/featured-articles/index.scss [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+  padding: 0 1rem;
+  align-items: flex-start;
+
+  h2 {
+    font: var(--type-heading-h4);
+    margin-top: 0;
+  }
+}
+
+.tile-container {
```
Comment (caugner) [inline client/src/homepage/featured-articles/index.scss:16]: Should this be inside the `.featured-articles`?

File: client/src/homepage/featured-articles/index.scss [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+  max-width: 52rem;
+  gap: 1rem;
+
+  @media screen and (min-width: $screen-md) {
+    flex-direction: row;
+    padding: 0 1rem;
+  }
+}
+
+.article-tile {
```
Comment (caugner) [inline client/src/homepage/featured-articles/index.scss:28]: ditto

File: client/src/app.scss [hunk 4]
```diff
@@ -21,36 +22,55 @@
...
-  --type-article-p: 400 1rem/2 var(--font-body); /* 16px/200% */
+  /* based on the following type-scale https://type-scale.com/?size=16&scale=1.200&text=MDN%20Web%20Docs&font=Inter&fontweight=400&bodyfont=body_font_default&bodyfontweight=400&lineheight=1.75&backgroundcolor=%23ffffff&fontcolor=%23000000&preview=false */
+  --type-heading-h1-font-size: 2.488rem;
+  --type-heading-h2-font-size: 2.074rem;
+  --type-heading-h3-font-size: 1.728rem;
+  --type-heading-h4-font-size: 1.44rem;
+  --type-heading-h5-font-size: 1.2rem;
+  --type-base-font-size-rem: 1rem;
+  --type-smaller-font-size: 0.833rem;
+  --type-tiny-font-size: 0.694rem;
```
Comment (caugner) [inline client/src/app.scss:42]: I think it would be better if these variables shared a common prefix (and I'm not sure what the `type-` means):

```suggestion
  --font-size-smaller: 0.833rem;
  --font-size-tiny: 0.694rem;
```

File: client/src/document/ingredients/browser-compatibility-table/feature-row.tsx [hunk 5]
```diff
@@ -276,14 +281,17 @@ function CellIcons({ support }: { support: bcd.SupportStatement | undefined }) {
...
+    isOnlySupportedWithAltName(support) ||
+    supportItem.flags ? (
     <div className="bc-icons">
       {isOnlySupportedWithPrefix(support) && <Icon name="prefix" />}
       {hasNoteworthyNotes(supportItem) && <Icon name="footnote" />}
       {isOnlySupportedWithAltName(support) && <Icon name="altname" />}
       {supportItem.flags && <Icon name="disabled" />}
     </div>
-  );
+  ) : null;
```
Comment (caugner) [inline client/src/document/ingredients/browser-compatibility-table/feature-row.tsx:294]: To avoid repetition:

```ts
const icons = [
      {isOnlySupportedWithPrefix(support) && <Icon name="prefix" />},
      {hasNoteworthyNotes(supportItem) && <Icon name="footnote" />},
      {isOnlySupportedWithAltName(support) && <Icon name="altname" />},
      {supportItem.flags && <Icon name="disabled" />},
].filter(Boolean);

return (icons.length ? `<div className="bc-icons">{icons}</div>` : null);
```

File: client/src/document/ingredients/browser-compatibility-table/atoms/_bc-history-link.scss [hunk 6]
```diff
@@ -0,0 +1,37 @@
+.bc-history-link {
```
[the remark this answers is not in the document]
Comment (schalkneethling) [reply client/src/document/ingredients/browser-compatibility-table/atoms/_bc-history-link.scss:1]: Hmmm, I think you actually removed these right? Not sure why the merge with `main` did not remove them.

File: client/src/app.scss (hunk 4 above)
Comment (schalkneethling) [reply client/src/app.scss:42]: I probably meant to call it `typography` no idea why I did not 😆

Comment (schalkneethling) [reply client/src/app.scss:42]: Ah no, I see. This was the convention already in place so I just followed. I believe something like what you suggest here is better but, perhaps it can be a cleanup post this merge? I can change it now but, it will touch potentially even more files than what this already touches.

File: client/src/document/ingredients/browser-compatibility-table/feature-row.tsx (hunk 5 above)
Comment (schalkneethling) [reply client/src/document/ingredients/browser-compatibility-table/feature-row.tsx:294]:
```js
function CellIcons({ support }: { support: bcd.SupportStatement | undefined }) {
  const supportItem = getFirst(support);
  const icons = [
    isOnlySupportedWithPrefix(support) && <Icon name="prefix" />,
    supportItem && hasNoteworthyNotes(supportItem) && <Icon name="footnote" />,
    isOnlySupportedWithAltName(support) && <Icon name="altname" />,
    supportItem && supportItem.flags && <Icon name="disabled" />,
  ].filter(Boolean);

  return icons.length ? `<div className="bc-icons">{icons}</div>` : null;
}
```

File: client/src/app.scss (hunk 4 above)
Comment (danielhjacobs) [reply client/src/app.scss:42]: Suggestion from outsider: for now, change from `--type-smaller-font-size` and `--type-tiny-font-size` to `--type-font-size-smaller` and `-type-font-size-tiny`. Remove `type` in a follow-up PR.

Current uses of this convention do put the common word first (e.g. `--type-code-regular` and `--type-code-inline`)

File: client/src/document/ingredients/browser-compatibility-table/atoms/_bc-history-link.scss (hunk 6 above)
[the remark this answers is not in the document]
Comment (caugner) [reply client/src/document/ingredients/browser-compatibility-table/atoms/_bc-history-link.scss]: Oh, you're right.

File: Procfile.dev [hunk 7]
```diff
@@ -1,4 +1,3 @@
 server: yarn start:dev-server
 type-check: cd client && tsc --noEmit --watch
 web: yarn start:client
-ssr: yarn watch:ssr
```
Comment (caugner) [inline Procfile.dev:4]: Just saw this now, was this line removed intentionally?

File: client/src/app.tsx [hunk 8]
```diff
@@ -44,14 +44,21 @@ function Layout({ pageType, children }) {
...
+      {pageType === "document-page" ? (
+        <div className={`page-wrapper  ${category || ""} ${pageType}`}>
+          {children}
+        </div>
+      ) : (
+        <div className={`page-wrapper  ${category || ""} ${pageType}`}>
+          <TopNavigation />
+          {children}
+        </div>
+      )}
```
Comment (caugner) [inline client/src/app.tsx:61]: This can be deduplicated:

```suggestion
      {<div className={`page-wrapper  ${category || ""} ${pageType}`}>
          (pageType === "document-page" && <TopNavigation />)
          {children}
        </div>}
```

File: client/src/ui/_vars copy.scss [hunk 9]
```diff
@@ -0,0 +1,278 @@
+@use "./color-palette" as *;
```
Comment (caugner) [inline client/src/ui/_vars copy.scss]: This file looks like a VS Code artefact.

Comment (caugner) [reply client/src/ui/_vars copy.scss]: Fixed in 92c1fea.

File: client/src/app.tsx (hunk 8 above)
Comment (caugner) [reply client/src/app.tsx]: Fixed in 78378b823.

File: Procfile.dev (hunk 7 above)
Comment (caugner) [reply Procfile.dev:4]: I checked, and this was removed as part of 27353f572848b8f6cc98be1ce67c1e88d30d43dd.

Comment (caugner) [reply Procfile.dev]: Reverted via f1211d321.

File: client/src/app.scss (hunk 4 above)
Comment (caugner) [reply client/src/app.scss:42]: It's better than before, so I will resolve this thread for now.

File: client/src/document/index.scss [hunk 10]
```diff
@@ -54,6 +52,18 @@
...
+    @include mdn.uify();
+    &::after {
+      text-decoration-color: var(--category-color);
+    }
+  }
+
+  /* reduce the top margin of the interactive example heading */
+  h2:first-of-type {
+    margin-top: 2rem;
+  }
```
Comment (caugner) [inline client/src/document/index.scss:65]: This also affects the "Prerequisistes" section on http://localhost:3000/en-US/docs/Learn/HTML:

image

I would tend to remove this exception. Or, if there really should be less spacing before interactive examples, to add a CSS class to that heading via `EmbedInteractiveExamp.ejs`:

https://github.com/mdn/yari/blob/1c28a240f988803c175e62d3c28acc5cc055a7a5/kumascript/macros/EmbedInteractiveExample.ejs#L51

**Review by caugner — CHANGES_REQUESTED** [review]

**Comment by caugner** [comment]
@schalkneethling FYI I added a Changes section to the PR description, and I would add that list to the squash commit. Feel free to adjust and/or complete.

File: client/src/document/index.scss (hunk 10 above)
Comment (schalkneethling) [reply client/src/document/index.scss:65]: I actually did the second but, there is a Cheerio script that runs on build and it removed the class sadly.

Comment (schalkneethling) [reply client/src/document/index.scss:65]: I think this is OK for now in the context of the larger changes that form part of this. One can always go back and clean this up as part of the larger SASS/CSS refactor that I believe Florian has in mind.

**Comment by schalkneethling** [comment]
> @schalkneethling FYI I added a Changes section to the PR description, and I would add that list to the squash commit. Feel free to adjust and/or complete.

Looks fine to me, thanks @caugner!

**Review by caugner — APPROVED** [review]

**Review by caugner — CHANGES_REQUESTED** [review]
Sorry, noticed only now that the MDN Plus docs have a greyish background-color: http://localhost:3000/en-US/plus/docs/faq

image

vs

image

**Comment by caugner** [comment]
> the MDN Plus docs have a greyish background-color

This comes from here:

https://github.com/mdn/yari/blob/82882ae9820fd1dc075e02f07b50539e8d4e2876/client/src/ui/molecules/grids/_standard-page.scss#L15-L17

**Comment by caugner** [comment]
> This comes from here:

However, we cannot just remove it, because then the MDN Plus Collections page looks like this:

image

Currently, that page looks like this:

image

We're using an `<h2>` there, which caused the new `margin-bottom`, on top of the yellow-ish background-color.

**Comment by schalkneethling** [comment]
> > the MDN Plus docs have a greyish background-color
> 
> This comes from here:
> 
> https://github.com/mdn/yari/blob/82882ae9820fd1dc075e02f07b50539e8d4e2876/client/src/ui/molecules/grids/_standard-page.scss#L15-L17

I believe this should be `--background-primary` no?

**Comment by caugner** [comment]
Now we only need a fix for this:

image

This is caused by:

https://github.com/mdn/yari/blob/1c28a240f988803c175e62d3c28acc5cc055a7a5/client/src/document/index.scss#L336-L337

**Solution**: Add `align-items: center` to `.notification-card-description`.

**Review by caugner — APPROVED** [review]

**Comment by caugner** [comment]
The BCD table is not ideal when there are notes for some users:

image

This was slightly less visible before:

image

**Comment by schalkneethling** [comment]
> The BCD table is not ideal when there are notes for some users

I agree, I actually still think we should have all the icons on the top and the version numbers aligned at the bottom. Something to consider for the next iteration. Thank you so much for all the assistance on this @caugner! Much appreciated.
