### PR TITLE
cope with new slugs created

### LINKED ISSUE #677: watcher breaks when you add new content or change slug
Steps to reproduce:

1. `yarn clean && yarn start`
2. Create a new folder in `content/files/en-us/something`
3. Create a new `index.html` file there
4. Edit it once

```
5:09:54 PM watchcontent.1 |  change in /Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/somethingnew
5:09:54 PM watchcontent.1 |  (node:16015) UnhandledPromiseRejectionWarning: Error: /en-us/docs/glossary/png3 is not present in this.allTitles
5:09:54 PM watchcontent.1 |      at Builder.processFolder (/Users/peterbe/dev/MOZILLA/MDN/yari/content/scripts/build.js:1642:13)
5:09:54 PM watchcontent.1 |      at processTicksAndRejections (internal/process/task_queues.js:97:5)
5:09:54 PM watchcontent.1 |      at async onChange (/Users/peterbe/dev/MOZILLA/MDN/yari/content/scripts/build.js:872:37)
5:09:54 PM watchcontent.1 |  (node:16015) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
5:09:54 PM watchcontent.1 |  (node:16015) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Another thing you can do is to open any existing `index.html` and change the slug. 
Granted, you shouldn't be doing this anyway because editing a slug, manually, without adding the old slug to `_redirects.txt` is going to be a problem.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #677

Steps to test:

1. `yarn clean && yarn start`
2. Create a brand new folder: `mkdir content/files/en-us/somethingnew`
3. Save a new `index.html` in it. E.g.:
```
---
slug: Brandspankingnew
title: Brand spanking new
summary: BLa bla
---
<p>Hi!</p>

```
4. Save file. 
5. Go to http://localhost:3000 and expect to find it in the search and be able to go to it. 

Second Steps to test:

1. `yarn clean && yarn start`
2. Find an existing `index.html`. Eg. `emacs content/files/en-us/glossary/jpeg/index.html`
3. Change the `slug` to something new. 

Now, what we **could** do is be really smart. 
When a `processFolder()` is called from the watcher, it could check if this was a new slug but we can loop over all the values in `this.allTitles` to see if this file was already in there but had a different key. But this feels premature because I suspect that 99% of people will use your CRUD tools to rename slugs. And that'll deal with redirects.

### CODE REVIEW

**Comment by peterbe** [comment]
Crap! It helps if I read the documents: https://github.com/paulmillr/chokidar/issues/461#issuecomment-205903584

File: content/scripts/build.js [hunk 1]
```diff
@@ -1825,7 +1843,13 @@ class Builder {
...
   processFolderTitle(source, folder, allPopularities) {
     const { metadata } = getContent(source, folder, true);
-    const mdn_url = buildMDNUrl(metadata.locale, metadata.slug);
+    let mdn_url;
+    try {
+      mdn_url = buildMDNUrl(metadata.locale, metadata.slug);
+    } catch (err) {
+      console.warn(`The folder that caused the error was: ${folder}`);
+      throw err;
+    }
```
Comment (peterbe) [inline content/scripts/build.js:1852]: Explanation for this change:
First of all, it's off topic and not really related to the issue. Shame on me!
However, I find this really useful. 
When I was fumbling with my testing and messing with `index.html` files, I once accidentally messed up and created a `index.html` with front-matter that didn't have a `slug: ...` and you get a weird error. The error is still "good" in that it's necessary. What's so annoying about it is that you have no idea which folder it was that caused this. So, all this change does is that it "pauses the exception", logs the folder what was the context, and proceeds to throw again.

**Comment by Gregoor** [comment]
Thanks Peter, oversight on my part. I also could've helped you not having to stumble over ignoreInitial yourself 🙈 Ah well, good that we have it now. 🎉
