### PR TITLE
MacroExecutionError on circular page() macro calls

### LINKED ISSUE #1270: Memory OOM on /en-US/docs/Web/API/MediaSession/setActionHandler
The file that triggers the OOM crash is: https://github.com/mdn/content/blob/e7c50f5d2383924101236cbcedaf218648f311b9/files/en-us/web/api/mediasession/setactionhandler/index.html

To reproduce, simply open http://localhost:3000/en-US/docs/Web/API/MediaSession/setActionHandler in `yarn dev`
After a long time, you'll get something like this:

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100bfea43 node::Abort() (.cold.1) [/usr/local/Cellar/node/14.5.0/bin/node]
 2: 0x10008609d node::FatalError(char const*, char const*) [/usr/local/Cellar/node/14.5.0/bin/node]
 3: 0x100086206 node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node/14.5.0/bin/node]
 4: 0x10018cc95 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/14.5.0/bin/node]
 5: 0x10018cc3f v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/14.5.0/bin/node]
 6: 0x1002b2ff1 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/Cellar/node/14.5.0/bin/node]
 7: 0x1002b4354 v8::internal::Heap::MarkCompactPrologue() [/usr/local/Cellar/node/14.5.0/bin/node]
 8: 0x1002b1d3b v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/Cellar/node/14.5.0/bin/node]
 9: 0x1002b04e4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/Cellar/node/14.5.0/bin/node]
10: 0x1002b8654 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/14.5.0/bin/node]
11: 0x1002b86aa v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/14.5.0/bin/node]
12: 0x100294e11 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [/usr/local/Cellar/node/14.5.0/bin/node]
13: 0x10036b2a7 v8::internal::JsonParser<unsigned char>::MakeString(v8::internal::JsonString const&, v8::internal::Handle<v8::internal::String>) [/usr/local/Cellar/node/14.5.0/bin/node]
14: 0x10036a2c1 v8::internal::JsonParser<unsigned char>::ParseJsonValue() [/usr/local/Cellar/node/14.5.0/bin/node]
15: 0x100369db8 v8::internal::JsonParser<unsigned char>::ParseJson() [/usr/local/Cellar/node/14.5.0/bin/node]
16: 0x100369d4d v8::internal::JsonParser<unsigned char>::Parse(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::Object>) [/usr/local/Cellar/node/14.5.0/bin/node]
17: 0x10020bfa6 v8::internal::Builtin_Impl_JsonParse(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/Cellar/node/14.5.0/bin/node]
18: 0x10077d739 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/Cellar/node/14.5.0/bin/node]
19: 0x1ccf25a2d827
```

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #1270

### CODE REVIEW

File: kumascript/index.js [hunk 1]
```diff
@@ -13,7 +13,24 @@ const {
...
 const { HTMLTool } = require("./src/api/util.js");
 
-const renderFromURL = memoize(async (url) => {
+const DEPENDENCY_LOOP_INTRO =
+  'The following documents form a circular dependency when rendering (via the "page" and/or "IncludeSubnav" macros):';
+
+const renderCache = new Map();
+
+const renderFromURL = async (url, urlsSeen = null) => {
+  const urlLC = url.toLowerCase();
```
Comment (peterbe) [inline kumascript/index.js:22]: This just feels a bit weird. But it's necessary. 
The `renderFromURL` is given a URL that it needs to not mess with because it contains important information about the *caSe* of the URL. That URL is used to build live samples iframe `src` attributes for example. If you lowercase it (just for the benefit of the cache and the `urlsSeen`) you're changing it and it breaks how it gets used within the live sample macro. 

However, we should NOT be using `info.cleanURL`, like we do for prerequisites, because that one might use redirects which only makes sense when you're rendering macros. The original caller of this function comes ultimately from the CLI that builds all pages and there it can't be a redirect'ing URL.

**Review by escattone — APPROVED** [review]
Looks and works great, thanks @peterbe !
