### PR TITLE
fix(markdown): match folder only for h2m cli

### LINKED ISSUE #6607: markdown h2m cli will match prefix not folder and may not work on some folders
### Summary

markdown h2m cli has those problems:

1. the cli will match prefix not folder (which is unexpected), if we run command `yarn md h2m glossary/block --locale zh-CN --mode dry` the cli will process on both `glossary/block` and `glossary/block_cipher_mode_of_operation`
2. the cli will not work on folder like `web/css/_colon_-moz-only-whitespace` because of using `slug` to match the prefix see: <https://github.com/mdn/yari/blob/bfe87cd4c0a03d5f82c2d7809ea7c449b8a7a270/markdown/cli.ts#L172>

### URL

none

### Reproduction steps

run commands:

- yarn md h2m glossary/block --locale zh-CN --mode dry --verbose
- yarn md h2m web/css/_colon_-moz-only-whitespace --locale zh-CN --mode dry --verbose

### Expected behavior

only match folder and worked on some specific folders

### Actual behavior

-

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

_No response_

### Anything else?

_No response_

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### PR DESCRIPTION
**Pull request by yin1999**
## Summary

Fixes #6607.

### Problem

see issue.

### Solution

- for matching folder only, adding trailing slash to match folders only
- for working on some specific folder like `web/css/colon-moz-only-whitespace`, use `doc.fileInfo.folder` instead of `slug`

### Before

image

image

### After

image

image

### CODE REVIEW

File: markdown/cli.ts [hunk 1]
```diff
@@ -162,14 +162,18 @@ program
...
-      const slugPrefix = args.folder.toLowerCase().replace(/\\/g, "/");
+      const slugPrefix = args.folder.replace(/\\/g, "/");
       try {
         for (let doc of documents.iter()) {
           progressBar.increment();
           if (
             doc.isMarkdown ||
             // findAll's folderSearch is fuzzy which we don't want here
-            !doc.metadata.slug.toLowerCase().startsWith(slugPrefix)
+            !doc.fileInfo.folder
```
Comment (fiji-flo) [inline markdown/cli.ts:172]: Let's just split off the locale and not to the separator conversion.

**Review by fiji-flo — CHANGES_REQUESTED** [review]
I agree. However, how about just making this folder based. See other comments.

**Comment by awxiaoxian2020** [comment]
Hi, @yin1999 

Why when I merge your branch, there are some errors in vscode?

File: markdown/cli.ts [hunk 2]
```diff
@@ -161,15 +165,17 @@ program
         string,
         { offset: number; invalid: []; unhandled: [] }
       >();
-      // replace '\' with '/' for Windows path
-      const slugPrefix = args.folder.toLowerCase().replace(/\\/g, "/");
+      const folderPrefix = folder?.slice(0, -1);
```
Comment (fiji-flo) [inline markdown/cli.ts:168]: I didn't yet find the time to test this. But from reading it, it seems like this is removing the trailing slash again?

**Comment by fiji-flo** [comment]
I see there warning on main. Feel free to ignore for now. TS is having problems deducting the types.

File: markdown/cli.ts (hunk 2 above)
Comment (yin1999) [reply markdown/cli.ts:168]: Because the `Document.find` will return docs which was in `**path/to/folder/**`: <https://github.com/mdn/yari/pull/6608/files#diff-8b04a3903730a363dd6402fa699fa3ecb6b241c1be608b573b194fe2440cbf54R146-R153>

And the `doc.fileInfo.folder` will end with a slash (like `web/css/colon-moz-only-whitespace`), to match with folder, we can only match prefix here (only match `path/to/folder/**`).

Comment (yin1999) [reply markdown/cli.ts:168]: or we can add a slash in the end of `doc.fileInfo.folder`

Comment (yin1999) [reply markdown/cli.ts]: maybe add a trailing slash is better, fixed it.

**Review by fiji-flo — APPROVED** [review]
Looks good.Thank you 🙏
