### PR TITLE
fix: social links in footer lack discernable names

### LINKED ISSUE #1978: Footer social links don't have discernible names
The social links in the footer lack discernable names.

### PR DESCRIPTION
**Pull request by schalkneethling**
Add `aria-label` to ensure social links in footer have discernable names

fix #1978

### CODE REVIEW

**Review by mattiapontonio — COMMENTED** [review]
These labels are not pretty accurates:

I'm espeting this kind of sentence if the button is the "real follow button" so clicking on it lead to follow on Twitter.

Instead there are "only" links to page.

I suggested some here 
https://github.com/mdn/yari/issues/1942#issuecomment-739182470

File: client/src/ui/organisms/footer/index.tsx [hunk 1]
```diff
@@ -78,6 +78,7 @@ export function Footer() {
                 href="https://twitter.com/mozdevnet"
                 target="_blank"
                 rel="noopener noreferrer"
+                aria-label="Follow MDN on Twitter"
```
Comment (fiji-flo) [inline client/src/ui/organisms/footer/index.tsx:81]: Not to open a can of worms: I think on Kuma these only says "Twitter" which nicely ditches the l10n issue here.

**Review by fiji-flo — APPROVED** [review]
:+1:
