### PR TITLE
dry-run redirect argument as part of deletion

### LINKED ISSUE #4123: `content delete --redirect` fails to a broken state
If I run `yarn content delete --redirect` where the argument to `--redirect` contains a typo, then the `delete` command proceeds to incompletely delete the target page, putting the content into an annoying-to-fix state.

## What happens

Here's an example: I'm trying to delete `Web/API/BluetoothRemoteGATTService/getIncludedService` and redirect it to `/en-US/docsWeb/API/BluetoothRemoteGATTService` (note the `docsWeb` typo).

### Input
```
$ yarn content delete --redirect /en-US/docsWeb/API/BluetoothRemoteGATTService Web/API/BluetoothRemoteGATTService/getIncludedService
```

### Output

(the `$` is yarn, not me)

```
yarn run v1.22.10
warning ../../../../package.json: No license field
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/tool/cli.js delete --redirect /en-US/docsWeb/API/BluetoothRemoteGATTService Web/API/BluetoothRemoteGATTService/getIncludedService
Will remove 1 documents:
Web/API/BluetoothRemoteGATTService/getIncludedService
redirecting to: /en-US/docsWeb/API/BluetoothRemoteGATTService
? Proceed? Yes

error: The URL is expected to start with /$locale/docs/: /en-US/docsWeb/API/BluetoothRemoteGATTService

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Results

Only the source file is deleted; the deletion is not reflected in `_redirects.txt` or `_wikihistory.json`:

```
$ git status --short
D  files/en-us/web/api/bluetoothremotegattservice/getincludedservice/index.html
```

This is inconvenient. Because the source file no longer exists, I can't re-run `yarn content delete --redirect`; it fails with another error. Instead, I have to run `git restore --staged --worktree ./files/` before re-running the command.

## What I expect to happen

If the redirect isn't valid, then I expect `content delete` to exit with an error and leave the working tree unmodified.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #4123

```
▶ yarn tool delete --redirect /gargbage Web/API/BluetoothRemoteGATTService/getIncludedService
yarn run v1.22.10
$ node tool/cli.js delete --redirect /gargbage Web/API/BluetoothRemoteGATTService/getIncludedService

error: The URL is expected to start with /$locale/docs/: /gargbage

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And now it no longer executed the deletion part.

### CODE REVIEW

**Review by fiji-flo — APPROVED** [review]
👍

File: content/document.js [hunk 1]
```diff
@@ -676,6 +676,7 @@ function remove(
   const docs = [slug, ...children.map(({ metadata }) => metadata.slug)];
 
   if (dry) {
+    Redirect.add(locale, [[url, redirect]], { dry });
```
Comment (Elchi3) [inline content/document.js:679]: What if you want to delete a document without a redirect?

Comment (peterbe) [reply content/document.js:679]: Is that not possible to do? And if you do, it's a rare case where you don't need the CLI tool but can use good old `git rm` :)

Comment (Elchi3) [reply content/document.js:679]: I'm following the steps here: https://github.com/mdn/content#deleting-a-document and it doesn't seem to work anymore or the usage has changed and the docs need to be updated.  It feels a lot safer using the CLI to me anyway and the docs advice it, too.
