### PR TITLE
titles.json and sitemap urls

### LINKED ISSUE #554: titles.json and sitemaps have their URLs in lowercase
Steps to reproduce:

1. `yarn clean && yarn prebuild && node content build -l en-us`
2. `cat client/build/sitemaps/en-us/sitemap.xml | head`
3. `cat client/build/en-us/titles.json | head`

(Note, the `sitemap.xml` files aren't important because we're not planning to ship those to Google Search Console any time soon)

However, the correct spelling of the slugs/URIs is lost and is needed when you use the autocomplete search.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #554

Steps to test:

1. `yarn clean && yarn prebuild && ls -l client/build`
2. `node content build -l en-us -f glossary -l fr -l sv-SE`
3. `ls -l client/build` (note only the mentioned locales got built)
4. `less client/build/sv-se/titles.json` look at the case of the keys
5. `less client/build/sitemaps/fr/sitemap.xml` look at the case of the URLs within

### CODE REVIEW

**Comment by peterbe** [comment]
@Gregoor this is partially blocking the progress on the "web editor". Can you review it?

File: content/scripts/build.js [hunk 1]
```diff
@@ -919,26 +919,46 @@ class Builder {
       });
   }
 
-  /** `this.allTitles` is a map of mdn_url => object that contains useful
-   * for the SSR work. This function dumps just the necessary data of that,
-   * per locale, to the final destination.
+  /** `this.allTitles` is a map of mdn_url (lowercase) => object that
+   * contains useful for the SSR work. This function dumps just
```
Comment (Gregoor) [inline content/scripts/build.js:923]: nit: useful is not a noun
