### PR TITLE
fix: localized content notes

### LINKED ISSUE #3588: add banner to localized pages
### Intro
Let's add a banner to all localized pages for the 10 supported non-English locales. The banner has to account for two cases:
1. pages within the 6 active locales: `ru`, `ko`, `fr`, `ja`, `zh-CN`, and `zh-TW`
2. pages within the 4 inactive locales: `de`, `es`, `pl`, and `pt-BR`

### Location and look

Screenshot 2021-04-07 at 17 28 23

Let's go with @dalexsy's second mockup:
- Located just below the breadcrumb bar and much thinner than that bar
- Left justified text
- Highlighted background
    - **active** locales: light pastel yellow or whatever color @schalkneethling and @dalexsy feel is best
    - **inactive** locales: a color that provides more emphasis, that indicates more of a warning since these locales have no community maintaining them, perhaps a brighter yellow or very light red or whatever color @schalkneethling and @dalexsy feel is best

### Text
Let's hard code the translations of the English text into the banner for each locale.

#### Active locales
Let's go with translations of @ddbeck's text for the 6 active locales (text below shown for French as an example):
>This page was translated from English by the community. Learn more by joining the [French community on MDN](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#french_fr).

Where the language community links for each language would be as follows:
- "Chinese" (`zh-CN` and `zh-TW`): https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#chinese_zh-cn_zh-tw
- "French" (`fr`): https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#french_fr
- "Japanese" (`ja`): https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#japanese_ja
- "Russian" (`ru`): https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#russian_ru
- "Korean" (`ko`): TBD (@chrisdavidmills can provide this when it's ready)

#### Inactive locales
Let's go with translations of @chrisdavidmills' text for the 4 inactive locales:
> This page was translated from English by the community, but it is not actively maintained therefore it may be out-of-date. If you'd like to help maintain it, [find out how to activate inactive locales](https://github.com/mdn/translated-content#promoting-an-inactive-locale-to-tier-1).

### PR DESCRIPTION
**Pull request by schalkneethling**
Moves notecards into Yari.
Add localized content notes for active and inactive translated content.

## Not translated

Screenshot 2021-04-29 at 17 28 41

## Active translations

Screenshot 2021-04-29 at 17 28 34

## Inactive translations

Screenshot 2021-04-29 at 17 28 26

Fix #3588

### CODE REVIEW

File: client/src/document/index.tsx [hunk 1]
```diff
@@ -156,6 +157,8 @@ export function Document(props /* TODO: define a TS interface for this */) {
         </div>
       )}
 
+      {doc.isTranslated && <LocalizedContentNote doc={doc} locale={locale} />}
```
Comment (peterbe) [inline client/src/document/index.tsx:160]:
```suggestion
      {doc.isTranslated && <LocalizedContentNote doc={doc} locale={locale} isActive={doc.isActive} />}
```
That way, the source of truth about whether a locale is active or not is canonical and not dependent on business logic within that molecule. 
And within the molecule, use en-US as a fallback text if we don't have a translation.

File: client/src/document/molecules/localized-content-note/index.tsx [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+  return (
+    <div className={`localized-content-note notecard inline ${noteType}`}>
+      {`${noteContent.lead}`}
+      <a href={noteContent.url}>{`${noteContent.linkText}`}</a>
+    </div>
+  );
+}
+
+export function LocalizedContentNote({
+  doc,
```
Comment (peterbe) [inline client/src/document/molecules/localized-content-note/index.tsx:19]:
```suggestion
  isActive,
```

File: client/src/document/molecules/localized-content-note/index.tsx [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+  locale,
+}: {
+  doc: Doc;
```
Comment (peterbe) [inline client/src/document/molecules/localized-content-note/index.tsx:22]:
```suggestion
  isActive: boolean;
```

File: client/src/document/molecules/localized-content-note/index.tsx [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+      linkText:
+        "Si desea ayudar a mantenerlo, descubra cómo activar las configuraciones regionales inactivas.",
+      url:
+        "https://github.com/mdn/translated-content#promoting-an-inactive-locale-to-tier-1",
+    },
+  };
+  const currentActiveLocaleNoteContent = activeLocaleNoteContent[locale];
+  const currentInactiveLocaleNoteContent = inactiveLocaleNoteContent[locale];
+
+  if (doc.isTranslated && doc.isActive && currentActiveLocaleNoteContent) {
```
Comment (peterbe) [inline client/src/document/molecules/localized-content-note/index.tsx:56]:
```suggestion
  if (doc.isActive) {
```
And here, after, I think it should be something like this instead:
```
const noteContent = isActive && (activeLocaleNoteContent[locale] || activeLocaleNoteContent['en-US']) || inactiveLocaleNoteContent[locale] || inactiveLocaleNoteContent['en-US'];
```
That way, if if the `locale` is something like `zh-TW` and we don't have a translation for it it'll fallback to something like: `This locale active and community-driven bla bla`

Comment (peterbe) [reply client/src/document/molecules/localized-content-note/index.tsx:56]: Sorry for the confusing review but if you just `const noteContent = isActive && (....` you don't need an if statement at all. 
And there's no need to look at `isTranslated` because the component isn't even loaded if that's not the case.

File: client/src/document/molecules/localized-content-note/index.tsx [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+interface LocalizedNoteContent {
+  lead: string;
+  url: string;
+  linkText: string;
+}
+
+function getNote(noteContent: LocalizedNoteContent, noteType: string) {
+  return (
+    <div className={`localized-content-note notecard inline ${noteType}`}>
+      {`${noteContent.lead}`}
```
Comment (peterbe) [inline client/src/document/molecules/localized-content-note/index.tsx:12]:
```suggestion
      {noteContent.lead}
```

File: client/src/document/molecules/localized-content-note/index.tsx [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+      <a href={noteContent.url}>{`${noteContent.linkText}`}</a>
```
Comment (peterbe) [inline client/src/document/molecules/localized-content-note/index.tsx:13]:
```suggestion
      <a href={noteContent.url} className="external">{noteContent.linkText}</a>
```

**Review by peterbe — COMMENTED** [review]
Haven't done a deep review. Just some drive-by comments so far.

**Comment by schalkneethling** [comment]
Thank you for all the suggestions @peterbe. I feel so silly for not thinking about the fact that the component is only loading is `isTranslated` is true so, no need to check or even have it available inside the component 😸

**Comment by schalkneethling** [comment]
I also fixed the padding for the notes so now it uses the same amount of padding(on the sides) as the breadcrumbs.

**Review by peterbe — CHANGES_REQUESTED** [review]
I still think we should make the component agnostic of the `doc` object. 
It still doesn't make sense to test `doc.isTranslated` outside calling the component and then doing the same test again inside. I think if you *use* the component if the document is `!doc.isTranslated` it's a mistake in logic.

**Comment by peterbe** [comment]
Hang on. I see now that all my comments have been marked as resolved. Did you perhaps forget to push some local changes?

**Comment by schalkneethling** [comment]
> Hang on. I see now that all my comments have been marked as resolved. Did you perhaps forget to push some local changes?

Hmmmm, let me double check

**Comment by schalkneethling** [comment]
> Hang on. I see now that all my comments have been marked as resolved. Did you perhaps forget to push some local changes?

Indeed I did 😄  Pushed.

**Comment by peterbe** [comment]
> > Hang on. I see now that all my comments have been marked as resolved. Did you perhaps forget to push some local changes?
> 
> Indeed I did 😄 Pushed.

Yikes. And a rebase I see. 
Git mess-ups is like radioactive decay. They always happen to everyone but over time less and less frequently :)

**Comment by schalkneethling** [comment]
> > > Hang on. I see now that all my comments have been marked as resolved. Did you perhaps forget to push some local changes?
> > 
> > 
> > Indeed I did 😄 Pushed.
> 
> Yikes. And a rebase I see.
> Git mess-ups is like radioactive decay. They always happen to everyone but over time less and less frequently :)

Actually the rebase was intentional but was done before I marked the PR as ready for review. Then I opened it for review and never pushed :p

**Review by peterbe — COMMENTED** [review]
Screen Shot 2021-05-04 at 11 56 56 AM
Is it just me, or is there a missing whitespace after the dot?

**Comment by peterbe** [comment]
Here too. 
Screen Shot 2021-05-04 at 12 03 46 PM

**Comment by peterbe** [comment]
I know you didn't write the English text @schalkneethling but perhaps with help from @chrisdavidmills or @escattone or @ddbeck we can tune that sentence so it's a whee bit shorter?
Right now it's so long that it becomes 2 lines long on a regular big screen. 
Screen Shot 2021-05-04 at 12 16 15 PM

**Comment by ddbeck** [comment]
Wordsmithing solely for length:

> This page was translated from English by the community, but it's not maintained and may be out-of-date. To help maintain it, learn how to activate locales.

File: client/src/document/molecules/_notecards.scss [hunk 7]
```diff
@@ -0,0 +1,173 @@
...
+    border-color: $red-300;
+    color: $neutral-100;
+  }
+
+  &.deprecated {
+    @include set-notecard-icon-only("~@mdn/dinocons/emojis/thumbs-down.svg");
+  }
+}
+
+.localized-content-note {
```
[the remark this answers is not in the document]
Comment (schalkneethling) [reply client/src/document/molecules/_notecards.scss]: No real reason. Mainly two things:

1. It is such a small piece of SASS I thought I would just have it live along with the rest of the notecard SASS
2. This way I am also sure the cascade behaves the way I expect/want

With that said, I did move it to its own file and simply import it in after the main `notecards` import.

File: client/src/document/molecules/localized-content-note/index.tsx [hunk 8]
```diff
@@ -0,0 +1,77 @@
...
+    es: {
+      lead:
+        "Esta página fue traducida del inglés por la comunidad, pero no se mantiene activamente, por lo que puede estar desactualizada.",
+      linkText:
+        "Si desea ayudar a mantenerlo, descubra cómo activar las configuraciones regionales inactivas.",
+      url:
+        "https://github.com/mdn/translated-content#promoting-an-inactive-locale-to-tier-1",
+    },
+  };
+
```
Comment (peterbe) [inline client/src/document/molecules/localized-content-note/index.tsx:70]: Instead of a different URL for each one, how about 
```javascript
const activeLocaleURL = "https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#active_locales";
const inactiveLocaleURL = "https://github.com/mdn/translated-content#promoting-an-inactive-locale-to-tier-1";
```
and then remove it from the `activeLocaleNoteContent` and `inactiveLocaleNoteContent` instead.

File: client/src/document/molecules/localized-content-note/index.tsx [hunk 9]
```diff
@@ -0,0 +1,77 @@
...
+        "Der Inhalt dieser Seite wurde von der Community übersetzt, jedoch wird er nicht mehr aktiv gepflegt und kann daher veraltet sein. Wenn du mithelfen möchtest, kannst du",
+      linkText:
+        "hier herausfinden wie deaktivierte Übersetzung reaktiviert werden.",
+      url:
+        "https://github.com/mdn/translated-content#promoting-an-inactive-locale-to-tier-1",
+    },
+    "en-US": {
+      lead:
+        "This page was translated from English by the community, but it's not maintained and may be out-of-date. To help maintain it, ",
+      linkText: "learn how to activate locales.",
```
Comment (peterbe) [inline client/src/document/molecules/localized-content-note/index.tsx:57]: I think it's weird that just this portion is part of the text. Those last 5 words are action words which is good but then it shouldn't include the end of the sentence.
```html
<!-- GOOD -->
<a href="...">learn how to activate locales</a>.
```
```html
<!-- WEIRD -->
<a href="...">learn how to activate locales.</a>
```

I think it would make more sense, to make the `linkText` the whole sentence instead.

File: client/src/document/index.scss [hunk 10]
```diff
@@ -7,6 +7,8 @@
 @import "~@mdn/minimalist/sass/mixins/utils";
 
 @import "./molecules/breadcrumb-locale-container";
+@import "./molecules/notecards";
+@import "./molecules/localized-content-note/";
```
Comment (peterbe) [inline client/src/document/index.scss:11]:
```suggestion
@import "./molecules/localized-content-note";
```
more consistent I suppose.

File: client/src/document/molecules/localized-content-note/index.tsx (hunk 8 above)
Comment (schalkneethling) [reply client/src/document/molecules/localized-content-note/index.tsx:70]: Sure, I went by what was "specd" in the issue but did wonder about it as well.

**Comment by peterbe** [comment]
Who helped with the Spanish translation? Can we ask that persons to revisit it since the English original has changed to a much shorter version. 
Screen Shot 2021-05-05 at 9 46 29 AM

We can of course do this later if we have to.

File: client/src/document/molecules/localized-content-note/index.tsx [hunk 11]
```diff
@@ -0,0 +1,57 @@
+function getNote(noteLinktext: string, noteType: string) {
+  const url =
+    noteType === "neutral"
+      ? "https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#active_locales"
```
Comment (peterbe) [inline client/src/document/molecules/localized-content-note/index.tsx:4]:
```suggestion
      ? "/en-US/docs/MDN/Contribute/Localize#active_locales"
```
and then...

File: client/src/document/molecules/localized-content-note/index.tsx [hunk 12]
```diff
@@ -0,0 +1,57 @@
...
+      : "https://github.com/mdn/translated-content#promoting-an-inactive-locale-to-tier-1";
+  return (
+    <div className={`localized-content-note notecard inline ${noteType}`}>
+      <a href={url} className="external">
```
Comment (peterbe) [inline client/src/document/molecules/localized-content-note/index.tsx:8]:
```suggestion
      <a href={url} className={!url.startsWith('/') ? 'external' : undefined}>
```

File: client/src/document/molecules/_notecards.scss [hunk 13]
```diff
@@ -0,0 +1,164 @@
...
+
+    background-color: $red-400;
+    border-color: $red-300;
+    color: $neutral-100;
+  }
+
+  &.deprecated {
+    @include set-notecard-icon-only("~@mdn/dinocons/emojis/thumbs-down.svg");
+  }
+}
```
Comment (peterbe) [inline client/src/document/molecules/_notecards.scss:164]: So I'm guessing once this lands, you can delete notecards from minimalist, is that right?

**Review by peterbe — APPROVED** [review]
With nits. 
Well done! Thanks for working hard on it.

File: client/src/document/molecules/_notecards.scss (hunk 13 above)
Comment (schalkneethling) [reply client/src/document/molecules/_notecards.scss:164]: Indeed, the release is waiting in the wings.

**Comment by schalkneethling** [comment]
> We can of course do this later if we have to.

Yeah, let's land it and we can update it after. It was a community member that posted the translation on the issue I believe. We also need some additional translations but for now, we will just fallback to en-US
