### PR TITLE
fix: Mark as warning when image host not resolved

### LINKED ISSUE #2623: Fixing flaw from commandline crashes with network timeout
Ran across this running as part of a larger glob of folders, but can reporduce as below with the official `yarn content flaws`

```
$ yarn content flaws Glossary/State_machine
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/tool/cli.js flaws Glossary/State_machine
RequestError: Timeout awaiting 'request' for 10000ms
    at ClientRequest.<anonymous> (Z:\mdn-content\node_modules\got\dist\source\core\index.js:953:65)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (Z:\mdn-content\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at Timeout.timeoutHandler [as _onTimeout] (Z:\mdn-content\node_modules\got\dist\source\core\utils\timed-out.js:36:25)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1611185586707,
    socket: 1611185586708,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1611185596717,
    abort: undefined,
    phases: {
      wait: 1,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 10010
    }
  },
  event: 'request'
}
RequestError: Timeout awaiting 'request' for 10000ms
    at ClientRequest.<anonymous> (Z:\mdn-content\node_modules\got\dist\source\core\index.js:953:65)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (Z:\mdn-content\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at Timeout.timeoutHandler [as _onTimeout] (Z:\mdn-content\node_modules\got\dist\source\core\utils\timed-out.js:36:25)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1611185586707,
    socket: 1611185586708,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1611185596717,
    abort: undefined,
    phases: {
      wait: 1,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 10010
    }
  },
  event: 'request'
}

error: Timeout awaiting 'request' for 10000ms

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not sure if `postimg.org` is currently hitting some issues, but I think if it does hit some network issue, it should print a warning instead of a hard crash

### PR DESCRIPTION
**Pull request by nschonni**
Fixes #2623

### CODE REVIEW

**Comment by nschonni** [comment]
@peterbe I think it's OK to treat these as a 404 since it's another case were the resource can't be resolved

File: build/flaws.js [hunk 1]
```diff
@@ -528,7 +528,10 @@ async function fixFixableFlaws(doc, options, document) {
         newSrc = path.basename(destination);
       } catch (error) {
         const { response } = error;
-        if (response && response.statusCode === 404) {
+        if (
+          (response && response.statusCode === 404) ||
+          error.code === "ETIMEDOUT"
```
Comment (peterbe) [inline build/flaws.js:533]: What if the server is just having a bad day? Or your computer might think it's connected to the internet, because it's connected to the router, but it's actually not succeeding in any packets. What would happen in either case is that you missing the opportunity to try to download (and correct) this image. What the correct thing to do in that case, is to try a little bit later. 

However, I think it's quite *plausible* that you're even in this mess because, actually, the domain is gone so it times out (ie. there's not even a server who wants to respond that the image is 404ing). 
And given that there's little harm (you just can't turn the external image into a local image today), perhaps it's just fine. 

The only thing I object to is the "lie" that we're checking for `ETIMEDOUT` but say "Skipping ${flaw.src} (404)". 
So, can you break up this if statement so it becomes something like this:
```javascript
if (statuscode===404) {
  console.log(chalk.yellow(`Skipping ${flaw.src} (404)`));
  continue;
} else if (ETIMEDOUT) {
  console.log(chalk.yellow(`Skipping ${flaw.src} (request timed out)`));
  continue;
} else {
  throw
}
```

**Review by peterbe — CHANGES_REQUESTED** [review]
A mix of pedanticism and pragmatism.

File: build/flaws.js (hunk 1 above)
Comment (Ryuno-Ki) [reply build/flaws.js:533]: Or imagine your connection goes away during download …

Comment (nschonni) [reply build/flaws.js]: Broke up the warnings

**Review by peterbe — APPROVED** [review]

**Comment by peterbe** [comment]
See if you can figure out a way, in your VSCode to *not* squash the commits. Please.
