### PR TITLE
fix(bcd): show previous version in range when feature was removed

### LINKED ISSUE #6667: BCD tables include the `version_removed` in the version range
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1417902 filed again for the new MDN setup.

The problem is clearly illustrated by things that were in EdgeHTML (Edge 12-18) but are not in new Chromium-based Edge 79+:
https://developer.mozilla.org/en-US/docs/Web/API/DocumentType#browser_compatibility

It looks as though support was in Edge 12-79, but it was in Edge 12-18.

---

From duplicate https://github.com/mdn/yari/issues/3971:

> Take a look at this table:
> https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/replacesClientId#browser_compatibility
> 
> The data for Edge being rendered here is:
> ```
> "edge": {
>   "version_added": "18",
>   "version_removed": "79"
> },
> ```
> 
> This is rendered as "18 — 79" on a red background. I think the natural interpretation of this that the feature was in versions 18-79, but the correct interpretation is that it was in Edge 18 only.
> 
> I think the logic here should be:
> - The displayed end range is the version *before* `version_removed` in BCD.
> - If that is the same as the start range, show just a single number on red, "18" in this case.

### PR DESCRIPTION
**Pull request by danielhjacobs**
## Summary

Fixes #6667

### Problem

The version range showed the version where support was removed as well, which was confusing.

### Solution

Get version before that version using a helper function, and show that version number instead.

---

### Before

https://developer.mozilla.org/en-US/docs/Web/API/DocumentType#browser_compatibility

Screenshot from 2022-11-16 11-59-04

### After

http://localhost:3000/en-US/docs/Web/API/DocumentType#browser_compatibility

Screenshot from 2022-11-16 11-50-41

### CODE REVIEW

**Comment by foolip** [comment]
That looks much better!

File: client/src/document/ingredients/browser-compatibility-table/utils.ts [hunk 1]
```diff
@@ -191,3 +191,20 @@ export function getCurrentSupport(
...
   return getFirst(support);
 }
+
+export function getPreviousVersion(
+  version: BCD.VersionValue | string | undefined,
+  browser: BCD.BrowserStatement
+): BCD.VersionValue | string | undefined {
+  if (browser && typeof version === "string") {
+    const browserVersions = Object.keys(browser["releases"]).sort(
+      (a, b) => Number(a) - Number(b)
```
Comment (foolip) [inline client/src/document/ingredients/browser-compatibility-table/utils.ts:201]: Browser versions can't be correctly sorted as numbers, you'll need something like the npm compare-versions package.

Comment (danielhjacobs) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts:201]: Oh yeah.  The browser info I had looked at could be interpreted as decimals safely. But I see deno and Node JS can not be (deno has 1.10 after 1.9 and Node JS has 0.10.0 etc.

I'm busy for the rest of the day but I'll look into this tomorrow.

Comment (danielhjacobs) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts]: Added compare-versions and using it now. The new "After" picture shows 1-4.4.3 instead of 1-4.4 for Webview Android, which is the correct range.

File: client/src/document/ingredients/browser-compatibility-table/utils.ts [hunk 2]
```diff
@@ -191,3 +193,20 @@ export function getCurrentSupport(
   // Default (likely never reached)
   return getFirst(support);
 }
+
+export function getPreviousVersion(
+  version: BCD.VersionValue | string | undefined,
+  browser: BCD.BrowserStatement
+): BCD.VersionValue | string | undefined {
```
Comment (caugner) [inline client/src/document/ingredients/browser-compatibility-table/utils.ts:200]: `VersionValue` already includes `string` (and `null`, for that matter), and I don't think we'll ever get `undefined`:

```suggestion
export function getPreviousVersion(
  version: BCD.VersionValue,
  browser: BCD.BrowserStatement
): BCD.VersionValue {
```

File: client/src/document/ingredients/browser-compatibility-table/utils.ts [hunk 3]
```diff
@@ -191,3 +193,20 @@ export function getCurrentSupport(
...
+  if (browser && typeof version === "string") {
+    const browserVersions = Object.keys(browser["releases"]).sort(
+      compareVersions
+    );
+    const currentVersionIndex = browserVersions.indexOf(version);
+    if (currentVersionIndex && currentVersionIndex > 0) {
```
Comment (caugner) [inline client/src/document/ingredients/browser-compatibility-table/utils.ts:206]: `Array.indexOf` should always return a `number`:

```suggestion
    if (currentVersionIndex > 0) {
```

**Review by caugner — CHANGES_REQUESTED** [review]
LGTM, just two nits (I think).

File: client/src/document/ingredients/browser-compatibility-table/utils.ts (hunk 2 above)
Comment (danielhjacobs) [reply client/src/document/ingredients/browser-compatibility-table/utils.ts]: Done, though worth noting I copied that from here, so it may also be worth changing:
https://github.com/mdn/yari/blob/f59e4c8382648e65596e673f74bfe90bf0b20003/client/src/document/ingredients/browser-compatibility-table/utils.ts#L97-L100

**Review by caugner — APPROVED** [review]

**Comment by caugner** [comment]
Thank you @danielhjacobs! 🎉

**Comment by caugner** [comment]
Hm, for some reason it doesn't work on prod (although deployed): https://developer.mozilla.org/en-US/docs/Web/API/DocumentType#browser_compatibility 🤔

**Comment by caugner** [comment]
> Hm, for some reason it doesn't work on prod (although deployed): https://developer.mozilla.org/en-US/docs/Web/API/DocumentType#browser_compatibility 🤔

It looks like `browser.releases` only has the last 3 entries on prod:
image

That's because retired releases are not added to the `bcd.json`:

https://github.com/mdn/yari/blob/9a46d5434ba0ac15ee95a77b379d862421470a02/build/cli.ts#L199-L211

**Comment by danielhjacobs** [comment]
> https://github.com/mdn/yari/blob/837e5d00d28dd8507f58846836db4e0dd71e7534/build/document-extractor.ts#L482

Well that function seems useful, could avoid the `compare-versions` dependency by re-using it.

I assume the right thing to do then would be to add `version_supported_last` (as suggested in https://bugzilla.mozilla.org/show_bug.cgi?id=1417902#c) to infoEntry around here:
https://github.com/mdn/yari/blob/837e5d00d28dd8507f58846836db4e0dd71e7534/build/document-extractor.ts#L474

At that part of the code, are all the browsers still available in `browsers`?

**Comment by danielhjacobs** [comment]
Opened https://github.com/mdn/yari/pull/7614
