### PR TITLE
fix: conditionally add skip to lang menu link

### LINKED ISSUE #2756: Fix language selector skip link
Currently, we have a skip link that points to the language selector, however,

1. We only have this on the homepage and here there is in fact no language selector at the moment
2. We do not have this on other pages on MDN Web Docs even though a language selector does exist and would be useful as a skip to target

We should address both the above issues and also, ensure that the skip link, links to the `select` input as it is a natively focusable element.

See https://github.com/mdn/yari/issues/2755 for additional context.

### PR DESCRIPTION
**Pull request by schalkneethling**
Conditionally adds the skip to lang menu link to the a11y nav based on the presence of `docs` in the URL.

I tested this on the homepage, docs page, and settings page. It only shows the "Skip to select language" skip link on docs pages.

fix #2756

### CODE REVIEW

File: client/src/ui/molecules/a11y-nav/index.tsx [hunk 1]
```diff
@@ -24,6 +25,12 @@ export function A11yNav() {
     });
   }
 
+  React.useEffect(() => {
+    if (document && document.location.pathname.includes("docs")) {
```
Comment (Gregoor) [inline client/src/ui/molecules/a11y-nav/index.tsx:29]: I think we should use `useParams` instead, as that value is reactive, i.e. updates when the site changes, thus triggering that effect to re-run. Right now it only re-runs incidentally.

(another case where we use it, for a different thing https://github.com/mdn/yari/blob/6f66eb8f670699766ea8be46a50accf72ddafe1d/client/src/document/toolbar/edit-actions.tsx#L57)

File: client/src/ui/molecules/a11y-nav/index.tsx [hunk 2]
```diff
@@ -46,6 +53,18 @@ export function A11yNav() {
...
       </li>
+      {showLangMenuSkiplink && (
+        <li>
+          <a
+            id="skip-select-language"
+            href="#select-language"
+            onClick={sendAccessMenuItemClick}
+            onContextMenu={sendAccessMenuItemClick}
+          >
+            {"Skip to select language"}
```
Comment (Gregoor) [inline client/src/ui/molecules/a11y-nav/index.tsx:64]:
```suggestion
            Skip to select language
```
No need to quote strings, same thing for the anchors

File: client/src/ui/molecules/a11y-nav/index.tsx (hunk 1 above)
Comment (schalkneethling) [reply client/src/ui/molecules/a11y-nav/index.tsx]: As discussed on Slack I switched to using `useLocation`

File: client/src/ui/molecules/a11y-nav/index.tsx (hunk 2 above)
Comment (schalkneethling) [reply client/src/ui/molecules/a11y-nav/index.tsx]: Updated the other instances as well. Thanks!

File: client/src/ui/molecules/a11y-nav/index.tsx [hunk 3]
```diff
@@ -24,6 +27,12 @@ export function A11yNav() {
     });
   }
 
+  React.useEffect(() => {
+    if (location.pathname.includes("docs")) {
+      setShowLangMenuSkiplink(true);
+    }
+  }, [location]);
```
Comment (peterbe) [inline client/src/ui/molecules/a11y-nav/index.tsx:34]: I'm not sure this is necessary. Lemme test something.

**Review by peterbe — CHANGES_REQUESTED** [review]
No need to do this client-side. 
See https://github.com/schalkneethling/yari/pull/443

**Comment by peterbe** [comment]
Sorry for stomping into a PR I wasn't asked to review but I saw the notification and couldn't help to open the link and noticed that there was more convenient way to do it.

**Comment by peterbe** [comment]
Note, this is a bit iffy in that my suggestion isn't just a refactor. It's genuinely different. 
If you do google search and click on the link to the MDN home page, you get no "Skip to language". If you next click to client-side navigate to a document (which we don't have any such links yet) the hidden a11y-nav links won't change. 
But doing it in SSR means less stuff that needs to happen during client-side rendering.

**Review by Gregoor — APPROVED** [review]
Good point @peterbe! Aand looks good to me, thanks @schalkneethling.

**Review by peterbe — APPROVED** [review]
