### PR TITLE
fix in string interpolation

### LINKED ISSUE #1004: Make headlines permalink-able
Let's do whatever it takes to make it performant, non-obtrusive, intuitive, and accessible to link to headings. 
In today's `master` the only way you can make a link to a heading is if you scroll up and find the TOC in the sidebar (on mobile it's much more hidden). 

Note! I think we should still keep the TOC tables in the sidebar. 

There are two potential ways to do permalink-able headings. The way npmjs.com and github.com does READMES
that there's a little "chain icon" that appears to the left (or to the right) when you hover over the link. 
Screen Shot 2020-07-31 at 7 27 32 AM

Another approach is to simply turn every heading into a "self-link" like docs.github.com does. 
[Example page](https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot)
The headings are basically like this:

```html
<h3 id="enabling-github-dependabot-version-updates-for-actions">
  <a href="#enabling-github-dependabot-version-updates-for-actions">
    Enabling GitHub Dependabot version updates for actions</a></h3>
```

The advantages of that are that it requires 0 CSS and 0 JS to make it happen, and it works without a mouse device.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #1004

See https://github.com/mdn/yari/issues/1004#issuecomment-673632588

These are the kind of mistakes we're likely to make when we rush things. But that's the world we're (currently) living in.

### CODE REVIEW

**Comment by peterbe** [comment]
@schalkneethling I'm going to r=me this one.

File: client/src/document/ingredients/prose.tsx [hunk 1]
```diff
@@ -8,7 +8,7 @@ export function ProseWithHeading({ id, section }) {
   return (
     <>
       <h2 id={id}>
-        <a href={`#${id}`} title={`Permalink to {section.title}`}>
+        <a href={`#${id}`} title={`Permalink to ${section.title}`}>
```
Comment (schalkneethling) [inline client/src/document/ingredients/prose.tsx:11]: Doh!
