### PR TITLE
Ensure browsers in BCD tables are always rendered in the correct order

### LINKED ISSUE #6314: Wrong browser order in BCD
### Summary

Mobile browsers are included in the desktop column and vice versa.
This bug got introduced in 4978102cc5065da0d2a093a88a8ff25c6dfa7305.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-child#browser_compatibility

### Reproduction steps

1. Just open a link with a BCD table

### Expected behavior

image

### Actual behavior

image

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Screenshot

_No response_

### Anything else?

_No response_

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### PR DESCRIPTION
**Pull request by queengooborg**
This PR fixes #6314 by enforcing a specific order for the browsers to render in.  In #6308, the code was adjusted to filter for browsers matching the platforms specified; however, this did not enforce any specific order.  Additionally, the original code used a `Set` to generate the list of browsers, which does not actually guarantee an order of values; with both that plus the fact that it's destructured into an array anyways, this PR creates an array instead to ensure a specific order.

### CODE REVIEW

File: client/src/document/ingredients/browser-compatibility-table/index.tsx [hunk 1]
```diff
@@ -47,19 +47,28 @@ function gatherPlatformsAndBrowsers(
...
+  // Add browsers in platform order to align table cells
+  for (const platform of platforms) {
+    browsers.push(
+      ...(Object.keys(browserData).filter(
+        (browser) => browserData[browser].type === platform
+      ) as bcd.BrowserNames[])
+    );
+  }
+
+  //
```
Comment (caugner) [inline client/src/document/ingredients/browser-compatibility-table/index.tsx:61]:
```suggestion
  // Filter WebExtension browsers in corresponding tables.
```

**Review by caugner — APPROVED** [review]

**Comment by caugner** [comment]
Thank you @queengooborg!
